### ISSUE TITLE
[BUG] Using tolerance="tap" in module screw_hole() ALSO reduces the size of the hole for the screw head

### ISSUE THREAD

**Issue by LenStruttmann** [revarbat/BOSL2#1001]
Using module screw_hole() with tolerance="tap" or tolerance="self tap" reduces the diameter of the hole for the screw threads, but it also reduces the diameter of the hole needed for the screw head.  The screw head will no longer fit into the hole created.

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>
include <BOSL2/screws.scad>

$fn = 24;

screw("M3,5", head="socket", drive="hex", thread="none" );

translate( [ 0, 5, 0 ] )
#screw_hole("M3,5", head="socket");

translate( [ 0, -5, 0 ] )
%screw_hole("M3,5", head="socket", tolerance="tap");

```

**Expected behavior**
The diameter of the hole for the screw head should not be reduced.

**Screenshots**

**Comment by adrianVmariano** [comment]
Yeah, that's not good.  I have a fix.  If you need a work around, set head_oversize.
