### ISSUE TITLE
Add a function to convert a 2D child polygon to a list-of-points path/region

### ISSUE THREAD

**Issue by DeflateAwning** [revarbat/BOSL2#1005]
**Is your feature request related to a problem? Please describe.**
I'm trying to do the following, in order:
1. Import an STL file.
2. Take the projection of that STL file.
3. Linear extrude that projection 2d child polygon with `rounded_prism()`, with rounded edges 

To complete this currently though, `rounded_prism()` requires a path argument (list of points) instead of a 2d child shape.

**Describe the solution you'd like**
I'd like a function named `convert_2dshape_to_path()` which accepts a 2d child shape, and returns a list-of-points.

Such a function could be used to solve my problem, inserting it between Step 2 and Step 3.

**Describe alternatives you've considered**
An alternative feature may be to update `rounded_prism()` to accept a 2d child shape.

**Comment by revarbat** [comment]
Sadly it is not yet possible in OpenSCAD to convert geometry to point lists or VNFs. There are some code change proposals that may in the future make this possible, but at the rate that OpenSCAD adopts changes, I predict this won't be viable for another few years.

**Comment by adrianVmariano** [comment]
I think we can close this issue because it's impossible.
