### ISSUE TITLE
[BUG] square_threaded_nut fails to render 

### ISSUE THREAD

**Issue by bob-ewart** [revarbat/BOSL2#1012]
**Describe the bug**
The 2022-12-16 version of BOSL2 fails to render a square threaded nut with:
ERROR: CGAL error in 
CGALUtils::applyBinaryOperator difference: CGAL 
ERROR: assertion violation!
Expr: itl != it->second.end()
File: /usr/include/CGAL/Nef_3/
SNC_external_structure.h
Line: 1144

It worked with the 2022-11-17 version of BOSL2

**Code To Reproduce Bug**
```
`include <BOSL2/std.scad>
include <BOSL2/threading.scad>
square_threaded_nut(nutwidth=12, id=8, h=12, pitch=3);
'
```

**Expected behavior**
It should render the nut without errors as did the 2022-11-17 version of BOSL2.

**Screenshots**
![image](https://user-images.githubusercontent.com/13387457/209561995-66c176e6-8d1c-4dc4-a2ed-31cbd602f676.png)

**Additional context**
- OpenSCAD Version:  Tested the same on 2022.06.26 and 2022.12.25.nightly

**Comment by adrianVmariano** [comment]
I think I have this fixed in the latest PR.
