### ISSUE TITLE
[BUG] Rendering snap pins only shows half the structure in OpenSCAD UI

### ISSUE THREAD

**Issue by dclaze** [revarbat/BOSL2#1013]
**Describe the bug**
Rendering snap pins only renders half the structure when using OpenScad UI.

> NOTE: Rendering appears to work as expected using CLI command.

1. Open OpenSCAD in UI
2. Paste below code
3. Click render button
4. See only half of snap pin

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>;
include <BOSL2/joiners.scad>;

snap_pin("small");
```

**Expected behavior**
Expected to render double sided pin, but only half is rendered

**Screenshots**
<img width="802" alt="example_snap_pin" src="https://user-images.githubusercontent.com/1400324/209586343-16894e32-3286-4c82-a11e-6257777957d1.png">

**Additional context**
- OpenSCAD Version: 2022.03.02
- Other libraries used: N/A

**Comment by adrianVmariano** [comment]
I am not able to duplicate your problem.  Your code produces the full pin both on preview or render for me, either in the stable 2019 version or in the nightly build.  (I don't have 2022.03.02).  

Side note:  your $fn is too small.

**Comment by revarbat** [comment]
I also cannot reproduce it in OpenSCAD 2022.08.22 (git ea8950bd3).
On an unrelated note, the pointy ends have too much overhang to print cleanly without support.  I don't see any reason that they *need* to be that pointy, though.  If the points were pulled back to be at a 45º overhang, they should print without support rather nicely.

**Comment by revarbat** [comment]
This fixes the overhang, I think:
```diff
diff --git a/joiners.scad b/joiners.scad
index 38bdfa0..7cf7a98 100644
--- a/joiners.scad
+++ b/joiners.scad
@@ -754,8 +754,10 @@ module _pin_shaft(r, lStraight, nub, nubscale, stretch, d, pointed)
    down(extra) cylinder(r = r, h = lStraight + extra);
    up(lStraight) {
       zscale(stretch) {
-         sphere(r = r);
-         if (pointed) up(rPoint) cylinder(r1 = rPoint, r2 = 0, h = rPoint);
+         hull() {
+            sphere(r = r);
+            if (pointed) up(rPoint) cylinder(r1 = rPoint, r2 = 0, h = rPoint/stretch);
+         }
       }
    }
    up(d) yscale(nubscale) _pin_nub(r = r, nub = nub, h = lStraight - d);
```

**Comment by adrianVmariano** [comment]
I have printed it as it is and don't recall any problems.  It was based on a design that had been tested by multiple people, so I didn't change the design.  But I guess if you're certain it's an improvement and the pins will still fit well in the shaft....

Actually, your change seems to make almost no difference when a proper $fn value is used:

Original form:

![image](https://user-images.githubusercontent.com/26014420/210295845-9089d3f8-12cd-4ca6-ad5a-814a3f0f2e20.png)

With added hull():

![image](https://user-images.githubusercontent.com/26014420/210295885-d2152d9b-d8a8-40d7-873f-4d48e513ad3c.png)

Maybe what's needed is a minimum $fn constraint?  

After inspecting different $fn values it looks like the pointy cap just doesn't actually fit properly to the rest.  At high $fn the discrepancy is small and hard to notice, but it's still there,  so adding the hull() is probably the easiest solution.
