### ISSUE TITLE
[BUG] Exported .3mf from path_extrude2d using arc path has open edges

### ISSUE THREAD

**Issue by jreiberkyle** [revarbat/BOSL2#1014]
**Describe the bug**
I generated a 3d geometry using path_extrude2d() with a path generated using arc(). I exported it as .stl and as .3mf and then imported the files into PrusaSlicer. The .stl geometry has no errors but the .3mf geometry is flagged with an "open edges" error.

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>

path = arc(r=15, angle=270);
path_extrude2d(path) square(5);
```

**Expected behavior**
When exported to .3mf then imported to PrusaSlicer, the mesh would not have any errors.

**Screenshots**

<img width="422" alt="image" src="https://user-images.githubusercontent.com/2984664/209904004-baaa4149-8114-4518-b950-b2708ad0ea10.png">

<img width="791" alt="image" src="https://user-images.githubusercontent.com/2984664/209904054-10e40950-094c-475c-bacf-47bd10607cca.png">

**Additional context**
- BOSL @ 9c92e3ce0204e634a7446580625f6c8ed4a83140
- OpenSCAD Version: 2021.01
- Other libraries used: PrusaSlicer 2.5.0+MacOS+x64
- OS: MacOS 11.7.1

**Comment by revarbat** [comment]
This is a bug in OpenSCAD, not in BOSL2.
