### ISSUE TITLE
distributors.scad matrix functions

### ISSUE THREAD

**Issue by revarbat** [revarbat/BOSL2#1018]
It would be nice if distributors.scad modules had function variants that returned lists of transformation matrices, one per each copy.

```openscad
mats = zrot_copies(n=5, r=50);
```

Or, if given `p=`, return a list of transformed coordinates/paths/etc:

```openscad
rgn = zrot_copies(n=5, r=50, p=rect(20));
// Equivalent to:
// rgn = [for (mat = zrot_copies(n=5, r=50)) apply(mat, rect(20))];
```

**Comment by revarbat** [comment]
Entertaining (and redundant) side effect – generating paths like

```openscad
path = arc_copies(n=10, r=50, sa=60, ea=180, p=[0,0,0]);
```

**Comment by adrianVmariano** [comment]
I don't understand: why does applying `zrot` or `arc_copies` to `p=[0,0,0]`  do anything interesting?

Should arc_copies syntax be brought into more alignment with arc?
