### ISSUE TITLE
Add knurling to pco1881_cap()

### ISSUE THREAD

**Issue by sej7278** [revarbat/BOSL2#103]
Just spent an hour making a pc01881 cap using BOSL1, then noticed you already had a function in BOSL2!

Only problem being that you never get a bottle top that's smooth. So could you either add knurling or vertical serations?

i managed to do it but it seemed a bit messy as i had to figure out the dimensions of the cylinder to diff against e.g:

```
difference()
{
    knurled_cylinder(l=12.2, d=32, helix=45);
    up(0.1) cyl(l=12.2, d=30.6);
}

down(6.1) pco1881_cap(1);
```

![image](https://i.imgur.com/5JkKPUn.png)

Also, any chance of a pc01810 variant, i just printed these 1881's only to find i don't have any bottles that use it (and they broke when i tried).

useful reference: http://www.imajeenyus.com/mechanical/20120508_bottle_top_threads/index.shtml

**Comment by revarbat** [comment]
Knurling and ribbing implemented via `texture=` argument.

**Comment by revarbat** [comment]
Added PCO 1810 neck and cap in bf407307c78902cd2dacbdeea1aca7807ba6b0e9

**Comment by sej7278** [comment]
that's excellent thanks!!!
