### ISSUE TITLE
Wiki:  Typographic nit in adj_opp_to_hyp()

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/BOSL2#1031]
The wiki reads:

> Given the length of the adjacent and opposite sides of a right triangle, returns the length of thee hypotenuse.

Should be: "...length of **the** hypotenuse."

...unless of course,  you were going for old English, in which case it would be:  "...length of **thine** hypotneuse."

**Comment by adrianVmariano** [comment]
Fixed in PR.

**Comment by revarbat** [comment]
Mayhaps `thee` dost ring most aright, but Eald Englisć be'est not in oure list of labors.

**Comment by RAMilewski** [comment]
Priceless!   Well played!
