### ISSUE TITLE
Docs:  interior_fillet hidden from neophytes

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/BOSL2#1058]
It took a fair bit of random scrolling for me find interior_fillet().

Perhaps an entry in either the topics or function index something like:

**fillet - _see interior_fillet()_**

**Comment by adrianVmariano** [comment]
Is there some reason not to rename it simply fillet()?

**Comment by adrianVmariano** [comment]
There is, after all, no exterior_fillet() that it competes with.

**Comment by RAMilewski** [comment]
That was my first thought, but then I suspected there might be some other arcane fillet lurking in parts of BOSL2 I've not yet explored.

**Comment by adrianVmariano** [comment]
We **try** to group related things together.  If you think there's a better place for interior_fillet() to go let us know.

**Comment by adrianVmariano** [comment]
I have renamed this in my PR.
