### ISSUE TITLE
Wiki: Shapes3d: cuboid example 16 is somewhat confusing

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/BOSL2#1060]
Why "rounding" a rectangle would produce an irregular hexagon is not immediately obvious.
It depends upon the interaction of the small size of the object and the default value (2) of $fs.

It _**is**_ a good example to point out the perils of ignoring $fa, $fs, and $fn, but that's not mentioned in the example's description.

**Comment by adrianVmariano** [comment]
Actually the example really needs a suitable $fn so that it rounds to make its point, which is that you can round away an entire corner.

**Comment by RAMilewski** [comment]
Or perhaps must multiply the dimensions by 5 or 10 so the small-size behavior of $fs doesn't overwhelm the rounding.

**Comment by adrianVmariano** [comment]
Fixed in the PR.
