### ISSUE TITLE
[BUG]Typo in wiki regarding distributors.scad

### ISSUE THREAD

**Issue by WernerP** [revarbat/BOSL2#1063]
On the page with the url

https://github.com/revarbat/BOSL2/wiki/distributors.scad

seems to be a typo in the section "Function/Module: zrot_copies()" at "When called as a function, *without* a p`"
The single quotation marks seems to make no sense

The full text
When called as a function, *without* a p`	` argument, returns a list of transformation matrices, one for each copy.
When called as a function, *with* a p`	argument, returns a list of transformed copies ofp=`.

**Comment by adrianVmariano** [comment]
I have this fixed in my PR.
