### ISSUE TITLE
Docs still refer to 'fillet'

### ISSUE THREAD

**Issue by TwoClocks** [revarbat/BOSL2#1071]
All the docs in the `shapres3d` section still refer to fillet, which no longer seems to exist.

It's been replaced w/ `interior_fillet` AFAICT.

**Comment by adrianVmariano** [comment]
I'm confused.  fillet() exists.  interior_fillet() is deprecated.  The docs should refer to fillet() anywhere they refer.  Can you point to a specific place that needs to be fixed?

**Comment by adrianVmariano** [comment]
I think the problem is that you're using an old version of BOSL2.  The manual documents the current version.  Also since the examples are produced by the code, they can't be wrong---they are necessarily what the current version actually does.
