### ISSUE TITLE
Dizzying rotations of edge masks

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/BOSL2#1074]
I find myself taking several tries to get the various edge masks rotated into the correct position.

Any chance of adapting the elegant strategy used by xcyl(), ycyl() and zcyl() to the various edge masks?

**Comment by RAMilewski** [comment]
Oh.   Good point.  I've been jockeying edge masks into position rather than using an attachment module.   Yet another beginner error.

In the Attachment Tutorial though, it would be helpful to have a paragraph at the end of  **Attachables** pointing out some of the more prominent !attachables (e.g. anything extruded from 2d?).  I spent a bunch of time puzzling over why recolor() didn't work on anything in example 8 of round_corners().

**Comment by adrianVmariano** [comment]
I think maybe putting the list of non-attachables at the beginning makes more sense.  There's already a list of overridden shapes there.  

BTW, linear_extrude, rotate_extrude, and polygon are not attachable, but linear_sweep, rotate_sweep and region are attachable.   And we just added null attachables, which should make it possible to also make some other modules that aren't colorable respond to recolor and color_this.

**Comment by adrianVmariano** [comment]
I didn't realized that the "Attachables" section actually is the beginning.  I added some stuff there.  And a bit more in the color section, since it didn't mention color_this().

**Comment by adrianVmariano** [comment]
@RAMilewski Any further thoughts on this, or should we close it?

**Comment by RAMilewski** [comment]
Nothing I can think of.  Thanks for the help!
