### ISSUE TITLE
trapezoid anchoring inconsistency

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#1092]
Trapezoid CENTER anchoring is different for the function than for the module.  

```polygon(trapezoid( w1=100, h=40,w2=70,shift=33));```

![image](https://user-images.githubusercontent.com/26014420/227717668-4c4d609f-f63f-4de7-a811-4bd3babf1b5d.png)

```trapezoid( w1=100, h=40,w2=70,shift=33);```

![image](https://user-images.githubusercontent.com/26014420/227717730-079e7a14-008b-4653-93e5-1b1a31b8209e.png)

The CENTER anchor is at the midpoint between the FRONT and BACK anchors, but the trapezoid is not created in its centered position.  It appears that reorient assumes that the native position is the CENTER position.  But also, that assumption seems to be important because various modules call the function form, so they might get confused if that isn't true.   If I take out the line that special cases the CENTER anchor in reorient() then the anchors are still different from each other, just with the trapezoid in a different place.  

Do we need a special anchor like "origin" to use to handle this general situation?  (That is, modules that call the function request "origin" anchoring which does what CENTER does now, and CENTER is changed to use the standard anchor procedure).

**Comment by adrianVmariano** [comment]
@revarbat Did you fix this when you fixed prismoid anchoring?

**Comment by revarbat** [comment]
I have not touched the 2D `trapezoid()`, so I believe this is not yet fixed.

**Comment by adrianVmariano** [comment]
Hmmm.   If you change reorient and didn't fix trapezoid() it will be producing displaced anchors.

**Comment by adrianVmariano** [comment]
Is this fixed now?

**Comment by revarbat** [comment]
This is fixed.
