### ISSUE TITLE
prismoid anchors broken when top is shifted

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#1093]
The same problem happens with prismoid that happens with trapezoid regarding CENTER with shift:

```
v=prismoid([100,100],[30,30], shift=40, height=30,anchor=CENTER);
vnf_polyhedron(v);
```

produces a prismoid centered in XY based on the base centerline, whereas 

```
prismoid([100,100],[30,30], shift=40, height=30,anchor=CENTER);
```

produces a prismoid centered on the half-height cross section, which I think is the current notion of where the CENTER anchor is supposed to be.

**Comment by revarbat** [comment]
This is a bug in `reorient()` which tries to shortcut processing of CENTER anchors.  It is incorrect for trapezoid/prismoid geometries.
