### ISSUE TITLE
"Hull" and "Intersect" anchoring unexplained.

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/BOSL2#1095]
In shapes2d.scad both star() and supershape() take an atype parameter with two valid choices "hull" and "intersect".
However there is no explanation of the difference between the two and no relevant examples.

**Comment by adrianVmariano** [comment]
I added an explanatory subsection in attachments.scad to try to explain this.  It's in the PR.

**Comment by RAMilewski** [comment]
That explains it all quite nicely.
