### ISSUE TITLE
VNF from text3d()

### ISSUE THREAD

**Issue by elxris** [revarbat/BOSL2#1131]
**Is your feature request related to a problem? Please describe.**
Documentation states that from text() or text3d() we can get an vnf but no function is defined.

**Describe the solution you'd like**
If possible, make that happen.

**Describe alternatives you've considered**
I don't think there are alternatives to that. As some functions are very useful with vnf structures.
I've considered to process the font externally to get the 2D paths.

**Example Code**
```
vnf = text3d("example text");
```

**Additional context**
No additional context

**Comment by adrianVmariano** [comment]
This is not possible, at least as things stand.  There is no way to get the information out of geometry, so when openscad creates text, that's it---there is no way to access it.  So you would have to do like you said and produce the text externally somehow.

**Comment by adrianVmariano** [comment]
The synopsis needs to corrected not to say that you can get a VNF.

**Comment by elxris** [comment]
@adrianVmariano yes, it should be updated as text(), text3d(), and path_text() all says that you can access the vnf. Thank you for answering. I hope this is possible in the future.

**Comment by adrianVmariano** [comment]
Thanks for identifying the offenders...though I can't find such a reference for text().   I fixed the other two and pushed a PR.

**Comment by elxris** [comment]
You're right, I think I did hallucinate that one.
