### ISSUE TITLE
[BUG] Slider does not match rail when you change the rail width.

### ISSUE THREAD

**Issue by Rickrat** [revarbat/BOSL2#1133]
**Describe the bug**
Cannot change the width of the rail, otherwise the slider does not match the rail.

**Code To Reproduce Bug**
```
translate([0, 0, 0]) rail(l=150, w=20, h=10, chamfer=2, ang=15);
translate([40, 0, 0]) slider(l=30, base=10, wall=4, $slop=0.2, spin=90);

```

**Expected behavior**
It should match.

**Comment by revarbat** [comment]
Err, you forgot to specify `w=20` in the second line.

**Comment by revarbat** [comment]
There may still be a dimensional mismatch, though.

**Comment by revarbat** [comment]
Nevermind.  Also missing `ang=15` in the second line.

```openscad
rail(l=150, w=20, h=10, chamfer=2, ang=15);
up(20) zflip() slider(l=30, w=20, ang=15, base=10, wall=4, $slop=0.2, spin=90);
```
<img width="343" alt="Screenshot 2023-05-18 at 12 17 00 AM" src="https://github.com/revarbat/BOSL2/assets/350001/6dd92509-a40b-4966-a20e-32f4e0604601">
