### ISSUE TITLE
Make download link easy to find

### ISSUE THREAD

**Issue by amatulic** [revarbat/BOSL2#1145]
The README page and the wiki tell me to "Download the .zip or .tar.gz release file for this library."

Well the repository here says under "Releases" in the right column, "No releases published".

So where is the download link, and why isn't it hyperlinked in any of the instructions?

The only link I can find is in the dropdown under the Code button: https://github.com/revarbat/BOSL2/archive/refs/heads/master.zip

If that is the download link, then please hyperlink it in the instructions.

**Comment by adrianVmariano** [comment]
The download link is now in the instructions.
