### ISSUE TITLE
text3d() default language is "em"? 

### ISSUE THREAD

**Issue by jon-gilbert** [revarbat/BOSL2#1156]
Looking at the default argument values for `text3d()`, I think there's a mistake in the default language setting:

https://github.com/revarbat/BOSL2/blob/e80fe3ea859e7bf336715d76b1ce7580a5a792f5/shapes3d.scad#L2915

> language="em"

As documented, `text3d()` is meant to have a default of "en". 

I don't have a specific reproducible use-case where changing the language within OpenSCAD scripts to something unknown causes problems, so probably not an urgent fix, but thought I'd point it out.

**Comment by adrianVmariano** [comment]
Fixed.
