### ISSUE TITLE
rename trace_polyline

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#119]
Consider renameing trace_polyline to stroke3d.  Also change the size arg to width to match stroke.   (Maybe also pline arg should be path?)

**Comment by revarbat** [comment]
I enabled use of `stroke()` for 3D lines as well as 2D lines.  Implemented in b6f39ce77b8765bcdc009fcdb2969ee4b0cd8b54
I think I'll leave `trace_polyline()`, though, as it's mostly for debugging purposes, with features for showing bezier controls and such.

**Comment by revarbat** [comment]
Thinking about moving `trace_polyline()` to debug.scad, and maybe renaming it to `debug_path()` or `trace_path()`.

Also, changing all references to "polyline" to "path" or "path3d".

**Comment by adrianVmariano** [comment]
Is trace_polyline necessary now that you have stroke working for 3d paths?

**Comment by revarbat** [comment]
`trace_polyline()` is specialized to do things like show the control points of a bezier, or the pathpoints in a polyline.
