### ISSUE TITLE
rot() returns incorrect matrix with from=, to=, and a=

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#123]
For matrix output the a= argument is ignored with from= and to=. 

    rot(from=[0,0,1], to=[0,0,1],a=45)

gives the same matrix as 

    rot(from=[0,0,1], to=[0,0,1],a=0)

**Comment by revarbat** [comment]
Fixed in 8a29e9e86b1a3bedf52b33fe219b5174e5de5f43
