### ISSUE TITLE
torus interface confusing / confusingly documented

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#126]
I had to read the code to figure out how to get the torus I wanted.  There's a bunch of different diameters and radii with unclear meaning and I wasn't able to figure it out from the docs.   (What's the "torus ring"?)   I'm not sure if there's a way to change the interface to be more clear, but as it stands it seems like maybe a picture is needed to explain the meaning of the different parameters.

**Comment by adrianVmariano** [comment]
Did you fix this?    I think so, except for extra "of" words in the arg list.

**Comment by revarbat** [comment]
Typos fixed.
