### ISSUE TITLE
regular_ngon anchors fail in functional version

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#136]
When I do pentagon(side=2, anchor=FRONT) as a module I get the correct result.  When I wrap it in polygon() I get an incorrect result, with the polygon position away from the axis.  

Also note that if I pass a text anchor like anchor="side0" I get a cryptic error instead of a message like "unknown anchor".

**Comment by revarbat** [comment]
This has been fixed by the internals refactoring of `attachment()` and the addition of `reorient()`.
