### ISSUE TITLE
attachable has no defaults?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#137]
Right now if I don't enforce default values for anchor, spin and orient I get somewhat cryptic message about inputs being of the wrong type.  

As you complained with regards to skin, if you plan to leave it this way and not set defaults, I think you should display an informative error message along the lines of 

    assert(is_def(anchor), str("anchor parameter not supplied to attachable.  Consider setting a default anchor value in the definition of the parent module ", parent_module(1)))

**Comment by revarbat** [comment]
Implemented in ff4c3146e827011b799dc0837ec09f21643f077a
