### ISSUE TITLE
drop assertion compatibility function?  Fix assert_in_list to avoid dummy variable?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#15]
Since you mentioned dropping compatibility functions I assume there's no reason to keep assertion() around.  

Also, assert_in_list bugs me because it forces the use of dummy variables, which are not necessary with the regular assert() call.  It seems like this should be reworked so that the in_list error can be asserted without the dummy variable by passing something to assert() instead of having the function do the work.   (Doing this will presumably also get rid of duplicated code in the module vs function.)

**Comment by revarbat** [comment]
Removed `assertion()`

**Comment by revarbat** [comment]
Also removed the duplicate code in module `assert_in_lint()`
