### ISSUE TITLE
Feature request: 3d egg

### ISSUE THREAD

**Issue by pimlie** [revarbat/BOSL2#1505]
**Is your feature request related to a problem? Please describe.**
 
There doesn't seem to be a way currently to create a 3d object with different radii to create shapes like 3d eggs, bell's and/or simple rocket nozzle's.

**Describe the solution you'd like**

A quick & easy way to create a 3d egg-like object with varying curved angle

**Describe alternatives you've considered**

- Using `rotate_extrude` on a 2d `egg` doesn't work as you can't rotate a shape within itself. So you can only create a fancy torus this way
- Onion's come close but have a fixed angle for the top cone, while an egg/bell shape has a varying curved angle for the top cone
- Teardrop's might maybe sort-of work in some use-cases if they'd support rounding edge. 

**Example Code**
na

**Additional context**

i'd consider:
- a 3d egg (🥚) a shape like the thing that comes out of a 🐔 and you use to make an omelet 🍳 
- a bell (🔔) as a 3d egg with cut-off bottom and maybe negative bottom chamfer/rounding
- a simple rocket nozzle as a 3d egg with cut-off bottom (probably to the maximum of the biggest circle)

I understand that this is probably already possible somehow, but given the available 3d shapes this one seems missing. Or in other words, basically the onion shape shouldn't have to exists and could probably be a variant of the 3d egg?

**Comment by adrianVmariano** [comment]
You just have to cut off half the egg:

```
rotate_extrude()
  right_half(planar=true)
    zrot(90)
      egg(100,40,30,120);
```
