### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by lar3ry** [revarbat/BOSL2#152]
In the Wiki/shapes.scad, chamfered is misspelled throughout (5 intances).
It should have only one 'f'.

**Comment by revarbat** [comment]
I found no place where `chamfered` was spelled `chamffered`, but I did see it spelled `chamferred` a bunch.  Fixed in 1cab868d8a0f099fec4fc5f36193cf97616e9a60

**Comment by lar3ry** [comment]
Oops. I had a typo and was too quick correcting it.
Thanks for finding it.
