### ISSUE TITLE
star produces counterclockwise output

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#154]
The star function produces counterclockwise output.  It should be clockwise, since that's the standard.

**Comment by revarbat** [comment]
Easiest way would be to do a `reverse_polygon()` before output, but if you want to make a cleaner fix to this, have at.

**Comment by adrianVmariano** [comment]
Should it be changed to align a point with the X axis?   Maybe the update should wait for a finalization of the anchoring method.

**Comment by revarbat** [comment]
This is dependent on the orientation decision in #122

**Comment by revarbat** [comment]
Fixed in 9f630018f166b8b505390631117eb7b2a48b2410
