### ISSUE TITLE
supershape is counterclockwise

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#155]
Supershape output should be clockwise for consistency.

**Comment by revarbat** [comment]
This is definitely tied to the orientation decision in #154

**Comment by revarbat** [comment]
Related to #154

**Comment by revarbat** [comment]
`glued_circles()` also appears to be CCW.

**Comment by revarbat** [comment]
Actually, I verify `supershape()` as already being clockwise.  However, it starts somewhat clockwise of X+, instead of on X+.

**Comment by adrianVmariano** [comment]
Uh, I'm confused:

```
s = supershape(step=0.5,m1=16,m2=16,n1=0.5,n2=0.5,n3=16,r=50);
echo(cc = polygon_is_clockwise(s));
echo(s[0]);
```

That was the code I wrote before posting this issue.  And the output I get:

```
ECHO: cc = false
ECHO: [31.8073, 0]
```
Output says it's NOT clockwise and it starts on the X+ axis.  

Does the direction it turns depend on parameter choice?

**Comment by revarbat** [comment]
Huh.  I have no idea.  Maybe it does, because the `polygon_is_clockwise()` test I ran with it returned true.

**Comment by revarbat** [comment]
```openscad
path = supershape(m1=4, n1=1/2, n2=1/2, n3=4);
stroke(path,width=0.01);
echo(polygon_is_clockwise(path));
// ECHO: true
```

**Comment by revarbat** [comment]
Nevermind.  Examination shows that I already applied a fix for it in my code, and forgot I had.

**Comment by adrianVmariano** [comment]
What about the business of not starting on the X+ axis?

**Comment by revarbat** [comment]
That was a side effect of my original fix, and has been corrected.

**Comment by revarbat** [comment]
`supershape()` and `glued_circles()` are both fixed for CW from X+ standardization, as is everything in shapes2d.scad.
