### ISSUE TITLE
[BUG] Warning: variable p not specified as parameter shapes2d.scad line 1147

### ISSUE THREAD

**Issue by kingadami** [revarbat/BOSL2#156]
**Describe the bug**
When using mask2d_roundover you get the following warning:
```
WARNING: variable p not specified as parameter, in file ../.local/share/OpenSCAD/libraries/BOSL2/shapes2d.scad, line 1147
```

Looking at attachable and reorient as references as well as other function/module pairs in shapes2d.scad, it looks like this may be a mistake?  For example the mask2d_cove module does not have the p parameter passed to attachable.

Can be reproduced with:
```
include <BOSL2/std.scad>;

mask2d_roundover(r=10);
```

**Expected behavior**
No warning

**Additional context**
- OpenSCAD Version: 2019.05
- Other libraries used: N/A

**Comment by revarbat** [comment]
Leftover from the `attachable()` refactoring.  Fixed now.  Verified the bug no longer appears anywhere else in the code.  0346b8a26695d1766319031d1955d85bdbc24c2a
