### ISSUE TITLE
arced_slot missing reference to height in attachable call

### ISSUE THREAD

**Issue by matthewfallshaw** [revarbat/BOSL2#157]
**Current (broken) behaviour**
``` openscad
arced_slot(h=10, d=30, sd=1.6, sa=-20, ea=20);
```
produces an arced_slot of the expected size, but spanning 10mm to 20mm below the XY plane.
<img width="719" alt="current behaviour" src="https://user-images.githubusercontent.com/5561/79631385-7077c480-819c-11ea-89b3-e872c2dc6531.png">

**Expected behaviour**
The above code should produce an arced_slot spanning between the XY plane and 10mm below that plane.
<img width="719" alt="expected behaviour" src="https://user-images.githubusercontent.com/5561/79631393-79689600-819c-11ea-8f5b-57ba6df51b40.png">

**Fix**
https://github.com/revarbat/BOSL2/blob/7ebb83a81d0f5d2d20353ce9c2a1919247421091/shapes.scad#L1328

I think this line just needs to be
``` openscad
	attachable(anchor,spin,orient, r1=r+sr1, r2=r+sr2, l=h) {
```

**Comment by revarbat** [comment]
Fixed as described in 1ecd2e798d21951db5689b478d0c7204f8d943de
