### ISSUE TITLE
[BUG] Thinning wall does not scale sensibly

### ISSUE THREAD

**Issue by bernd-wechner** [revarbat/BOSL2#160]
**Describe the bug**
A nice promising object but try this:

thinning_wall(h=5, l=8, thick=1);

Renders garbage. There is some implciit scale assumption in the thickness of the frame it seems.

(Would also be nice if it support orthogonal braces bit just diagonal, and allowed positioning them (to model, windows well but I digress).

**Code To Reproduce Bug**
```
thinning_wall(h=5, l=8, thick=1);
```

**Expected behavior**
I expect a smaller thinning wall than int he tutorials that use larger height and length.

**Screenshots**
![image](https://user-images.githubusercontent.com/7296506/80305602-1365b980-8801-11ea-964f-5d2b3f999c8b.png)

**Additional context**
- OpenSCAD Version: 2019.05
- Other libraries used: None

**Comment by revarbat** [comment]
Made default wall and strut based on thickness.
