### ISSUE TITLE
document circle_point_tangents, remove "find" from find_circle functions

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#174]
The docs say that circle_point_tangents returns "ANG" but never says what this return value is.  (Is this return, whatever it is, necessary/useful?  If you have the point of tangency you can compute angles if needed.)  

The find_circle_3points and find_circle_2tangents might be renamed without "find".  Also they return arrays of undef in the collinear case.  Should they instead issue an error?

**Comment by revarbat** [comment]
Agreed that the ANG is easily derived and just makes using `circle_point_tangents()` more complex.  Changing it to return just the list of tangent points.

**Comment by revarbat** [comment]
Renames implemented in 07beb712a2686a7e4ec738cfd8867736bb77352e
