### ISSUE TITLE
stroke fails for 3d inputs

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#180]
include<BOSL2/std.scad>
    stroke([[0,0,0],[0,0,5]]);

fails with errors about path2 unknown.

**Comment by lar3ry** [comment]
Works for me. No errors in preview or render.

**Comment by adrianVmariano** [comment]
Are you using last night's revision?  That's when it broke.

**Comment by lar3ry** [comment]
On 14 Jun 2020 at 15:10, adrianVmariano wrote:
> Are you using last night's revision? That's when it broke.

No. I had downloaded it a few days ago, and when I saw your posting "Latest 
update seems to have broken stroke for 3d inputs." I realized what had 
happened, and downloaded the latest today.

Sorry about that.

**Comment by adrianVmariano** [comment]
On Sun, Jun 14, 2020 at 04:01:13PM -0700, lar3ry wrote:
> On 14 Jun 2020 at 15:10, adrianVmariano wrote:
> > Are you using last night's revision? That's when it broke.
> 
> No. I had downloaded it a few days ago, and when I saw your posting "Latest 
> update seems to have broken stroke for 3d inputs." I realized what had 
> happened, and downloaded the latest today.
> 
> Sorry about that.

I'm not sure downloading the latest version is the right response to
learning that it's broken.

**Comment by lar3ry** [comment]
On 14 Jun 2020 at 16:03, adrianVmariano wrote:
> > > Are you using last night's revision? That's when it broke.
> >
> > No. I had downloaded it a few days ago, and when I saw your posting "Latest
> > update seems to have broken stroke for 3d inputs." I realized what had
> > happened, and downloaded the latest today.
> >
> > Sorry about that.
> 
> I'm not sure downloading the latest version is the right response to
> learning that it's broken.

Well, I don't mind if it's broken. In this particular case, I don't (so far) use 
stroke() anyway, and if something else is also broken, I don't mind finding 
out. I do realize it's a work in progress.

Actually, from now on, I'll keep the old one when I download a new one.

**Comment by adrianVmariano** [comment]
On Sun, Jun 14, 2020 at 04:08:44PM -0700, lar3ry wrote:
> 
> Actually, from now on, I'll keep the old one when I download a new one.

It's pretty easy to download old revisions if you need to.

**Comment by revarbat** [comment]
Argh.  Fixed in 3b07cf210b79956fe72708eda7757d029e57583e
