### ISSUE TITLE
Should functions accept $closed to indicate closed paths?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#189]
It might simplify code if we used $closed as an option for specifying that paths are closed.  This would allow things like:

    let($closed=true) stroke(smooth_path(offset(path_tangent(path))))

rather than having to specify closed=true on every single call.

**Comment by revarbat** [comment]
To be honest, this feels like something that will come back to bite us if implemented.

**Comment by adrianVmariano** [comment]
So you're saying you're nebulously concerned, but not sure why?

**Comment by revarbat** [comment]
This is relying on the bizarre side effects of $specialvars in a way that will hide bugs where calls inside nested functions get a $closed value that is not apparent at its call level.

**Comment by revarbat** [comment]
ie: the $closed variable can affect calls that are INSIDE the functions that the $closed is meant to be passed to.

**Comment by revarbat** [comment]
```openscad
function pathlen(x) = path_length(x);
...
let($closed=true) stroke(smooth_path(offset(path,r=pathlen(openpath))));
```

**Comment by revarbat** [comment]
I'm no longer nebulously concerned.  Not I'm concretely concerned.

**Comment by adrianVmariano** [comment]
I do see the point.  This could be addressed by doing

    function pathlen(x) = path_length(x,closed=false);

but yeah, in general I think you're right that it's asking for trouble.

**Comment by revarbat** [comment]
I'll mark this one as "will not implement", then.
