### ISSUE TITLE
slice gives deprecation warning when indices are too big [BUG]

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#22]
echo(slice([1,2,3,4,5],6,4));

gives 

    DEPRECATED: Using ranges of the form [begin:end] with begin value greater than the end value is deprecated.

Adding a step of 1 into the range fixes it.

**Comment by revarbat** [comment]
Fixed in f378b701512dd242296cf05ec0f63e3d7e48bc6d
