### ISSUE TITLE
median function incorrect

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#226]
The median function computes the average of the min and max of the input instead of computing the median (the value such that half the data is above and half below).  

Correct implementation can use sort() and then take middle entry.  At least, that's the easy option.  Not sure if we can make it faster by avoiding the construction of the actual sorted data, the so-called quickmedian algorithm, I think.

**Comment by revarbat** [comment]
The `median()` function was removed.  The one use of it was changed to a `mean(pointillist_bounds(x))`.  Closing.
