### ISSUE TITLE
replist fails for n=0

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#23]
When n=0 replist returns two copies of the input list.  

I don't know what they were thinking when they made a range [n:n-k] be the same as [n-k:n].   I almost wonder if we should just go through the code and add a step=1 for every range to prevent more of these bugs cropping up.  The fix:
```
function replist(val, n, i=0) =
	is_num(n)? [for(j=[1:1:n]) val] :
	(i>=len(n))? val :
	[for (j=[1:1:n[i]]) replist(val, n, i+1)];
```

**Comment by revarbat** [comment]
Fixed in f378b701512dd242296cf05ec0f63e3d7e48bc6d
