### ISSUE TITLE
cuboid with chamfers: odd result when edges=FRONIT

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#235]
The code
       cuboid([10,10,10], chamfer=-1, edges=FRONT);
produces a cube with chamfers that extend past the extent of the cube.   It's also a little confusing (and limiting) that you can't do this and get all four front edges chamfered.  There are no conflicts....  But maybe that's too hard.

**Comment by revarbat** [comment]
Fixed.
