### ISSUE TITLE
[BUG]split_polygons_at_each_y produces non simple polygons

### ISSUE THREAD

**Issue by RonaldoCMP** [revarbat/BOSL2#241]
All the functions split_polygons_at_ may generate non simple polygons even from simple polygon inputs:
     split_polygons_at_each_y([[[-1,1,0],[0,0,0],[1,1,0],[1,-1,0],[-1,-1,0]]],[0])
produces:
   [  [[0, 0, 0], [1, 0, 0], [1, -1, 0], [-1, -1, 0], [-1, 0, 0]]
      [[-1, 1, 0], [0, 0, 0], [1, 1, 0], [1, 0, 0], [-1, 0, 0]] ]
The second polygon is self-intersecting.

It is possible that the applications of those functions doesn't require their output polygons be simple but then the docs of the functions should clarify that.

**Comment by revarbat** [comment]
Fixed in 0210738
