### ISSUE TITLE
[BUG] warning if rot()

### ISSUE THREAD

**Issue by RonaldoCMP** [revarbat/BOSL2#243]
The call:

`rot([12,-49,40],planar=true)`

as a function is generating the following:

```
WARNING: cos() parameter could not be converted, in file ../affine.scad, line 72 
TRACE: called by 'cos', in file ../affine.scad, line 72. 
TRACE: called by 'affine2d_zrot', in file ../transforms.scad, line 349. 
TRACE: called by 'rot', in file test_quaternions.scad, line 289. 
TRACE: called by 'verify_f', in file test_quaternions.scad, line 289. 
TRACE: called by 'test_Q_to_matrix3', in file test_quaternions.scad, line 291. 
```

No error was reported and the docs are not clear if the call is invalid.

**Comment by revarbat** [comment]
Definitely an invalid call.  When `planar=true`, Euler angle triplets aren't valid. Only a single scalar angle. Really, the only reason `rot()` has a `planar=` argument, is so it can return an affine2d rotation matrix around the Z axis.

**Comment by RonaldoCMP** [comment]
Although, the call was presumably invalid and should produce an error, the function doc doesn't clarify the issue.

**Comment by revarbat** [comment]
I'm thinking it should be asserting a clearer error, as well as having clearer docs.

**Comment by revarbat** [comment]
I'll fix this one.
