### ISSUE TITLE
More range index bugs

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#25]
I started reading through arrays.scad for other places where indexing bugs appear due to the idiotic behavior of ranges that end before they start.   It looks like the following need fixing:

list_range (has two ranges that need a step of 1 added)
list_remove (has one range that needs the fix)
list_pad (but I already proposed a bigger change to that one)
list_trim can be cleaned up a bit once the 1 is added, and 
enumerate can also have the test for the empty list removed after the fix
pair and pair_wrap both need the fix, failing horribly on the empty list with the return [[undef,undef],[undef,undef]]
zip needs the fix in two places
transpose needs the fix as well, and then you can delete the check for empty list.  (Right now you get a bad result from tranpose([[],[]]) all though one could debate what the answer should be, probably not [[undef, undef], [undef, undef]]

You must not use list_insert much---it's completely broken due to typo: slide->slice.
flatten can be rewritten to use each.  Did I post that as an issue already somewhere?

Anyway, this behavior is pretty annoying, but at least adding the step of 1 in the range provides a quick and easy fix.  The main problem is tracking down all the cases.

**Comment by revarbat** [comment]
Fixed in 9a860c53ef0453482f3ae2df516a3f5c49353be8
