### ISSUE TITLE
checks from math, vector, affine

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#26]
I looked through more of the files for indexing errors.  

In math.scad, vmul and vdiv need the fix.  

For deltas the base case is wrong.  It will be right if you fix pair and take out the test for length<2.  (Diff of a single value should be the empty list...or I guess you could argue for undef, but that seems more likely to break something somehow.)

ident needs the fix.  (ident(0) gives a 2x2 matrix.)  

Another observation is that affine3d_apply is inefficient.  I'm not sure if it matters, but if the matrix product is m1*m2*m3...*m100* point it's much more efficient to group the computation as m1*(m2*(m3*(...*(m100*point)))) because then all the products are matrix * vector.  The way you're doing it the products are matrix*matrix.   This would only matter, I think for hundreds or maybe thousands of matrices multiplied together.

**Comment by revarbat** [comment]
Fixed in 4fb825ce14b8d6ced71e768a3cdfa9bbfbb1b98b
