### ISSUE TITLE
Emboss base object using 3D pattern

### ISSUE THREAD

**Issue by olemis** [revarbat/BOSL2#269]
**Is your feature request related to a problem? Please describe.**
There is no mutator to implement a quite common pattern consisting in adding and subtracting (at the same time) a pattern out of multiple base objects ... similar to stamping or [paper embossing](https://en.wikipedia.org/wiki/Paper_embossing#Embossing_types).

**Describe the solution you'd like**
The workflow should be as follows:

- Design a 3D mask model for the repetitive embossing pattern based on the following rules
  * Mask parts in Z+ sub-space will be added to base model
  * Mask parts in Z- sub-space will be subtracted out of base object
- Design multiple base objects 
- Apply mask upon them.

**Describe alternatives you've considered**
This can be done by implementing modules one-by-one for each particular case , but this approach is tedious and cumbersome. A data driven solution can be implemented once for multiple use cases.

**Example Code**

Mask 👇
![image](https://user-images.githubusercontent.com/538253/93556629-2b241280-f947-11ea-9dee-6c979273ec7f.png)

```
emboss() {
    mask();
    cube([6, 10, 3], center=true);
}
```

Result 👇
![image](https://user-images.githubusercontent.com/538253/93556637-30815d00-f947-11ea-878f-3f523d3d49ee.png)

This is a [real-life example](https://wikifactory.com/+OttoDIY/dozer/file/3DPrint/Dozer%20V%20push%20in%20control%20horn%20(5).stl) .

**Additional context**
A few more variations would be nice to have , e.g. plane in direction other than Z+ and base object located at a point in space.

**Comment by olemis** [comment]
I'll submit an initial patch soon.

**Comment by revarbat** [comment]
```openscad
module emboss() {
    assert($children==2);
    difference() {
        children(0);
        bottom_half() children(1);
    }
    top_half() children(1);
}
```

**Comment by revarbat** [comment]
This isn't exactly embossing. Not sure what to call it, though.

**Comment by revarbat** [comment]
The `top_half()` and `bottom_half()` modules sometimes need a size value.
Also, `difference()` and `union()` both want their shapes to overlap some.
```openscad
module emboss(s=1000, overlap=0.001) {
    assert($children==2);
    difference() {
        children(0);
        down(overlap) bottom_half(s) children(1);
    }
    up(overlap) top_half(s) children(1);
}
```
