### ISSUE TITLE
add epsilon to line_segment_intersection and segment_intersection

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#27]
It's funny that I didn't run into this problem until recently, but it seems like we need to add an epsilon to the endpoint checks, because my code is failing to find an intersection at the endpoints.  

So 

        int[1]<0 || int[1]>1 || int[2]<0 || int[2]>1 ? undef : int[0];

becomes

        int[1]<-eps || int[1]>1+1ps || int[2]<-eps || int[2]>1+eps ? undef : int[0];

and 

         int[2]<0 || int[2]>1 ? undef : int[0];

becomes

         int[2]<-eps || int[2]>1+eps ? undef : int[0];

**Comment by revarbat** [comment]
Got some typos there.

Fixed in 78510c0b33b103b9d68ee355af84a098caa4172b
