### ISSUE TITLE
[BUG] Nested attachment `diff()`s work incorrectly.

### ISSUE THREAD

**Issue by revarbat** [revarbat/BOSL2#270]
**Describe the bug**
If you have nested attachment `diff()`, which are trying to use the same tag name, then the inner `diff()` works incorrectly.

**Code To Reproduce Bug**
```
module shape1() {
    diff("hole slot")
    cyl(d=50, h=20, $tags="body") {
        cuboid([10, 51, 21], $tags="slot");
        cyl(d=30, h=21, $tags="hole");
    }
}

diff("hole")
cuboid(100) {
    attach(TOP) shape1($tags="hole");
}
```

**Screenshots**
The expected correct result is:
<img width="509" alt="Screen Shot 2020-09-18 at 6 10 52 PM" src="https://user-images.githubusercontent.com/350001/93655760-59066700-f9da-11ea-8c79-5782989fa02c.png">

The actual incorrect result is:
<img width="509" alt="Screen Shot 2020-09-18 at 6 04 03 PM" src="https://user-images.githubusercontent.com/350001/93655714-04fb8280-f9da-11ea-810a-6eed53ca0635.png">

The shape of `shape1()` is:
<img width="509" alt="Screen Shot 2020-09-18 at 6 04 53 PM" src="https://user-images.githubusercontent.com/350001/93655719-15abf880-f9da-11ea-959b-b4104c27108b.png">

**Comment by revarbat** [comment]
Simple example:
```openscad module shape2() {
  diff("hole")
    cyl(d=50, h=20, $tags="body") {
    cyl(d=30, h=21, $tags="hole");
    }
}

diff("xhole")
  cuboid(50) 
    attach(TOP) shape2($tags="xhole");
It gets the wrong answer even without any repeated tags.

**Comment by revarbat** [comment]
Fixed in the sense that you can now `diff()` an attached object that. is constructed with `diff()` itself.  However, the fix required makes it so that you can only use one `diff()`, `intersect()`, or `hulling()` on a parent object.

**Comment by adrianVmariano** [comment]
Do you mean you can have only two levels of recursions of diff()?  (Or those other operations?)

**Comment by revarbat** [comment]
You can do:
```openscad
diff("hole1")
shape1()
    diff("hole2")
    shape2()
        shape3($tags="hole2");
```
But not:
```openscad
diff("hole1")
diff("hole2")
shape1() {
    shape2($tags="hole1")
    shape3($tags="hole2");
}
```
or:
```openscad
diff("hole")
intersect("perim")
shape1() {
    shape2($tags="hole")
    shape3($tags="perim");
}
```

**Comment by revarbat** [comment]
You can have 2 or more `diff()`, as long as no two are for the same parent object.  For any one parent object, you can have exactly one `diff()`, `intersect()`, or `hulling()`.
