### ISSUE TITLE
anchors for xcyl(),  ycyl() are incorrect

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#271]
zcyl(r=1,l=5,anchor=BOTTOM)
      position(TOP)zcyl(r=.5, l=2.5,anchor=BOTTOM);

    ycyl(r=1,l=5,anchor=BACK)
      position(FRONT)ycyl(r=.5, l=2.5,anchor=BACK);

    xcyl(r=1,l=5,anchor=LEFT)
      position(RIGHT)xcyl(r=.5, l=2.5,anchor=LEFT);

Only the zcyl case produces the expected result, and that's because it's the same as cyl().  The other cases produce unexpected results.  The expected result is the two cylinders end-to-end in all three cases, but alined with the corresponding coordinate axis.

**Comment by revarbat** [comment]
Fixed in e86af33f525004c529f4a31fe34dc0736d700946
