### ISSUE TITLE
vmul work on other objects?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#280]
I needed to multiply two lists of matrices together, which is exactly what vmul does, but I can't use it because of the parameter check.  

Should the parameter check be relaxed?  Or is that to troublesome?  (Cases that would make sense would be lists of vectors and lists of matrices, and mixed lists of scalars / matrices.)

**Comment by revarbat** [comment]
`vmul()` is low level enough that I don't think it should be doing extensive arg checking. I'd vote to relate the checks.

**Comment by revarbat** [comment]
Implemented in cc29e07d8f649f573436beb4144e653c63a958d4
