### ISSUE TITLE
[BUG] cuboid rounding broken since speed optimizations

### ISSUE THREAD

**Issue by EarnyHerzberg** [revarbat/BOSL2#295]
4443be2 Merge pull request #286 from revarbat/revarbat_dev --> OK
63efb6f Merge pull request #287 from revarbat/revarbat_dev --> broken

Example:

include <BOSL2/std.scad>

cuboid(size = [15, 15, 4], rounding = 1, edges=[LEFT + FRONT, LEFT + BACK, RIGHT + FRONT, RIGHT + BACK]);
right(20)
cuboid(size = [15, 15, 4], rounding = 2, edges=[LEFT + FRONT, LEFT + BACK, RIGHT + FRONT, RIGHT + BACK]);
right(40)
cuboid(size = [15, 15, 4], rounding = 4, edges=[LEFT + FRONT, LEFT + BACK, RIGHT + FRONT, RIGHT + BACK]);
right(60)
cuboid(size = [15, 15, 4], rounding = 6, edges=[LEFT + FRONT, LEFT + BACK, RIGHT + FRONT, RIGHT + BACK]);

**Comment by revarbat** [comment]
Oooh.  Okay, that's fixable.

**Comment by revarbat** [comment]
Fixed in a53c77f

**Comment by EarnyHerzberg** [comment]
Thanks! Great library...
