### ISSUE TITLE
remove pie_slice

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#31]
arc() should replace pie_slice2d(), right?

**Comment by revarbat** [comment]
Until `arc()`s `N` argument can be defaulted away to be based on `segs()`, I'm keeping it in place.

**Comment by adrianVmariano** [comment]
Can't this be done by changing

     N = max(3,N),

to 

     N = max(3,is_def(N) ? N : ceil(segs(r)*angle/360)),

or something like that?

**Comment by revarbat** [comment]
That does it.  ac71eb67e8d852af72d67ef1108d2bc1412d6a07
