### ISSUE TITLE
[BUG] cuboid with a rounding = 0 fails to draw if $fn is > 96

### ISSUE THREAD

**Issue by DaleSchultz** [revarbat/BOSL2#318]
**Describe the bug**
a cuboid with a rounding = 0 fails to draw if $fn is > 96

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>
// cuboid rounding = 0 with $fn > 96 fails to draw
cuboid(p1=[ 0,0,0], size=[5,20,8], rounding = 0    ,$fn=96); // draws fine 
cuboid(p1=[10,0,0], size=[5,20,8], rounding = 0    ,$fn=97); // does not draw
cuboid(p1=[20,0,0], size=[5,20,8], rounding = 0.001,$fn=97); // draws fine
```

**Expected behavior**
Expect it to draw and render with $fn > 96

**Screenshots**
![fn96](https://user-images.githubusercontent.com/46095860/100553400-bbda7100-325b-11eb-886f-b585536400cc.png)

**Additional context**
a rounding value of .001 makes it work...

- OpenSCAD Version: 2019.05

- Other libraries used: only BOSL2/std.scad

**Comment by revarbat** [comment]
I cannot seem to reproduce this bug with either OpenSCAD 2019.05 or 2020.09.26

**Comment by DaleSchultz** [comment]
wow, what other settings are possible I wonder....
I spent hours narrowing it down to that combination. Let me restart OpenSCAD in case something is stuck there....

**Comment by DaleSchultz** [comment]
yup, after restarting OpenSCAD, it works perfectly!
OK I learned to do that too now when seeing strange things.
I wonder how I managed to get it into that state....

Really appreciate the whole library - many thanks, great work!

**Comment by DaleSchultz** [comment]
it is very similar in naure to

**Comment by revarbat** [comment]
I still cannot reproduce this.

**Comment by revarbat** [comment]
I did change `cuboid()` to specifically check if rounding=0 or chamfer=0 and just give `cube()`.
