### ISSUE TITLE
add rand_int() and shuffle()

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#32]
Because I needed to test other stuff I wrote these.  It's a bit tricky to decide if shuffle() is uniform, but I think it is.  The obvious way to write shuffle, building one entry at a time, is drastically slower.  

```


// Function: shuffle(list)
//
// Shuffles the input list into random order.
//
function shuffle(list) =
      len(list)<=1 ? list :
      let (
             rval = rands(0,1,len(list)),
             left = [for (i=[0:len(list)-1]) if (rval[i]<0.5) list[i]],
             right = [for (i=[0:len(list)-1]) if (rval[i]>=0.5) list[i]]
          )
       concat(shuffle(left), shuffle(right));

// Function: rand_int(min,max,N,seed)
//
// Return list of random integers in the listed range (inclusive)
function rand_int(min,max,N,seed=undef) =
  assert(max >= min, "Max value cannot be smaller than min")
  let (rvect = is_def(seed) ? rands(min,max+1,N,seed) : rands(min,max+1,N))
  [for(entry = rvect) floor(entry)];
```

It appears that the seed you pass affects only the one rands() call.  There's no simple way to get a series of random values from a desired seed.  (I guess you have to get all the random data you want all at once and then parcel it out.)  Ug.  That's why there's no seed option to shuffle().   I have no way to predict how many random values shuffle() will need, so it can't be done ahead.

**Comment by revarbat** [comment]
Added in 62f913a148509c4e3a829b8546d62d31af8d8e60
