### ISSUE TITLE
Normalize vectors.scad, quaternion.scad naming

### ISSUE THREAD

**Issue by revarbat** [revarbat/BOSL2#337]
quaternions.scad has functions almost all named with a Q_ prefix.
vectors.scad used a `v` prefix.

We should probably standardize on `v_` and `q_` prefixes.

**Comment by adrianVmariano** [comment]
There are also complex functions, currently with a C_ prefix.  (Currently used only for polynomial roots, I think.  There are a bunch more if the eigenvector code ever gets integrated.)

**Comment by revarbat** [comment]
Quaternions have been re-named to start with q_

**Comment by revarbat** [comment]
`vmul()` / `vdiv()` / `vabs()` / `vfloor()` / `vceil()` renamed to `v_` style.

**Comment by revarbat** [comment]
Complex math functions already have `c_` style names.
