### ISSUE TITLE
All path using functions call check_and_fix_path?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#368]
Should we make sure that all (most) path using functions (e.g. skin) call check_and_fix_path?

**Comment by revarbat** [comment]
Never liked that function name.  @adrianVmariano proposes just `fix_path()`.  I'm okay with that.

**Comment by revarbat** [comment]
Also suggests the need for a related routint to return a region from either a region or a path.  `fix_region()`?

**Comment by adrianVmariano** [comment]
Not sure...but I think this might be done at this point.   Are there any functions that still need modification?
