### ISSUE TITLE
[BUG] round_corner() fails with three points on a line

### ISSUE THREAD

**Issue by carstenfuchs** [revarbat/BOSL2#380]
**Describe the bug**
The code below fails with the given error message.

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>
include <BOSL2/rounding.scad>

polygon(
    round_corners(
        [
            [0, 0],
            [10, 0],
            [20, 1],    // change 1 to 0 to see the problem
            [30, -10],
        ],
        cut=0
    )
);
```

Resulting console output (with 1 changed to 0 in the above example):

Parsing design (AST generation)...
Saved backup file: /home/carsten/snap/openscad-nightly/2329/.local/share/OpenSCAD/backups/test-backup-knnS8416.scad
Compiling design (CSG Tree generation)...
ERROR: Assertion 'is_consistent(v)' failed: "Input to sum is non-numeric or inconsistent" in file BOSL2/math.scad, line 579 
TRACE: called by 'sum' in file BOSL2/rounding.scad, line 252 
TRACE: called by 'min' in file BOSL2/rounding.scad, line 250 
TRACE: called by 'round_corners' in file test.scad, line 5 
TRACE: called by 'polygon' in file test.scad, line 4 
Compiling design (CSG Products generation)...
Geometries in cache: 8
Geometry cache size in bytes: 2272
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
Normalized tree has 1 elements!
Compile and preview finished.
Total rendering time: 0:00:00.254

**Expected behavior**
Error free compilation as if the points were not colinear.

**Additional context**

- OpenSCAD Version: nightly 2021.01.08
- Other libraries used: today's (2021-01-13) BOSL2 master

**Comment by adrianVmariano** [comment]
I've fixed this in PR #383.   Collinear points will work as long as cut=0 or radius=0 at the point, since any larger rounding is impossible.   You can use nonzero joint value, in which case you get a bunch of extra collinear points added.  I was debating whether, in the case of "circle" rounding if I should add $fn points for consistency, or add 3 if $fn is not set.  Right now I'm adding only 2 points.
