### ISSUE TITLE
npt_threaded_rod:  reverse orientation for internal threads?  Add pipe option?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#414]
As I said in the chat, I think it might be better if internal threaded rods, which are differenced from objects, should appear by default in the correct orientation to be differenced, namely `orient=DOWN, anchor=TOP`.  As it stands, if you just naively make an object and use 

     diff("remove")
     object()
        attach(location) npt_threaded_rod(....,internal=true, $tags="remove");

then the difference will be upside-down, which won't really be obvious until the screw doesn't mate with the fabricated part due to the reversed taper.   Basically all the normal use cases with attach will require `orient=DOWN, anchor=TOP`.   Another issue is positioning so that the difference works properly without a slight offset.  I think this should be built in, rather than me having to shift it up.  

My other thought is that maybe there should be a pipe option to make the npt threaded rod (for external threads) hollow, so that it's easy to make a pipe.  I know in theory you can subtract a cylinder, but it's not obvious what the diameter should be to obtain a desired wall thickness.

**Comment by revarbat** [comment]
Regarding the internal pipe diameter, isn't that by definition the pipe size?  ie: 1/4" for 1/4 NPT?
