### ISSUE TITLE
$slop for clearances and documentation

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#433]
I don't love the $slop parameter for clearances, since it seems like it's not consistent from part to part, and it's also invisible.  I wonder whether default $slop should be zero, or if there's another better way to handle clearance.  

I think assuming $slop remains we need to make sure that every module that depends on it clearly documents that dependence.  (As noted in the other issue, a user was baffled by misfitting nut/screw pairs because of $slop.)  

Also should $slop be zero by default?

**Comment by revarbat** [comment]
`$slop` is 0.0 now.

**Comment by adrianVmariano** [comment]
Fixed by #989
