### ISSUE TITLE
Request: tutorial on how to create custom anchor points for attachments.

### ISSUE THREAD

**Issue by zumpchke** [revarbat/BOSL2#476]
The attachments system seems really powerful. Often openscad designs fall into a mess of dimensions and fudge factors (-w/2, h/2 + 0.1) etc.
Attachments are a good way of avoiding that. It would be useful to have a guide on how to create anchors for our own modules.

**Comment by revarbat** [comment]
This is definitely planned for the attachments tutorial.  Until I can sit down and write that, I can at least give an example here:
```openscad

**Comment by revarbat** [comment]
Tutorial implemented.
