### ISSUE TITLE
bezier helper functions

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#479]
bezpath = flatten([
        bezstart([0,0],45,40),
        beztang ([100,0], 90, 100),
        beztang ([200,0], 90, 100, 50),
        bezjoint([300,0],90,50,45,50),
        bezstop ([400,0],-45,20)
    ]);

    function bezstart(pt,a,r) = [pt, pt+polar_to_xy(r,a)];
    function beztang(pt,a,r1,r2) = [pt-polar_to_xy(r1,a), pt,pt+polar_to_xy(default(r2,r1),a)];
    function bezjoint(pt,a1,r1,a2,r2) = [pt-polar_to_xy(r1,a1), pt,pt+polar_to_xy(r2,a2)];
    function bezstop(pt,a,r) = [pt-polar_to_xy(r,a), pt];

Add this?  Possibly names should change?  Maybe bez_start, and bez_end?    To me "r" doesn't really make sense because I don't think of it as a radius, but not sure exactly what's better.

**Comment by revarbat** [comment]
These were already added:
https://github.com/revarbat/BOSL2/wiki/beziers.scad#section-bezier-path-construction
