### ISSUE TITLE
[BUG] -ish Source download does not include involute_gears.scad'.

### ISSUE THREAD

**Issue by lar3ry** [revarbat/BOSL2#523]
**Describe the bug**
involute_gears.scad not included in download of BOSL2-master.zip
Edit: changed involute_gears.scad to gears.scad, which worked. So example needs updating.

**Code To Reproduce Bug**
```
OpenSCAD/libraries/BOSL2/examples/BOSL2logo.scad
```

**Expected behavior**
Expected to see BOSL2 logo.

**Screenshots**

**Additional context**
- OpenSCAD Version: 2021.04.21.ai7788 (git d9d4a9757) 
- Other libraries used:

**Comment by revarbat** [comment]
BOSL2 is still a work in progress.  One recent change was renaming `involute_gears.scad` to `gears.scad`. Apparently I didn't catch all references to it.
