### ISSUE TITLE
rot should work in planar mode when given 2d input

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#55]
I did rot(45,[0,1]) and got back a 3-vector.  I had to explicitly give planar=true to get a 2-vector out.  This is wierd and unexpected.  If the input is 2d the output should be 2d.

**Comment by revarbat** [comment]
Hmm.  As I recall, the `planar` argument existed for the case of `foo = rot(45);` where it had no input point to judge 2D-ness from, and had to decide whether to return an affine2d or affine3d matrix.  Yes, if given a vector or path as input, it should be able to figure out on its own without the `planar` argument.

**Comment by adrianVmariano** [comment]
It doesn't.  

    echo(a=rot(45,p=[1,0]));
    ECHO: a = [0.707107, 0.707107, 0]

**Comment by adrianVmariano** [comment]
And yes, you need the planar argument for that other case with no point input.

**Comment by revarbat** [comment]
If given 2D input, but a 3D rotation, should it return a 3D value?  I would think so.

**Comment by adrianVmariano** [comment]
So something like rot([20,45,33],[1,1])?

Seems like it should either return 3d or an error.

**Comment by revarbat** [comment]
Fixed `rot()` to return 2D when passed 2D points in `p` and rotations are only around the Z axis.
If rotations aren't around the Z axis, 3D points will be returned.
