### ISSUE TITLE
threaded_rod assertion bug

### ISSUE THREAD

**Issue by SRKadam1** [revarbat/BOSL2#570]
**Describe the bug**
When trying to use `threaded_rod`, line 186 of `threading.scad` throws the error `Assertion '(_r1>(2*pdepth))' failed`.

**Code To Reproduce Bug**
Line 186 of `threading.scad`
```
dummy1 = assert(_r1>2*pdepth) assert(_r2>2*pdepth);
```
My code 
```
// scripts
include <BOSL2/std.scad> // threaded_rod() ( & cuboid, xcopies/ycopies)
include <BOSL2/threading.scad> // threaded_rod()
// screw parameters
thread2 = [0.06*in2mm,5*in2mm/32,in2mm/80]; // outer diameter, thread length, pitch
// throws error unless Line 186 is commented out
threaded_rod(d=thread2[0],l=thread2[1],pitch=thread2[2],internal=false);
threaded_rod(d=thread2[0],l=thread2[1],pitch=thread2[2],internal=true);
```

**Expected behavior**
The above code was written and worked in v1. Commenting out Line 186 leads to rod creation in agreement with v1. Without commenting out, there is no rod created.

**Comment by revarbat** [comment]
Fixed.
