### ISSUE TITLE
Add puzzlecut (or something like it)?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#58]
Consider adding something like this:

https://www.thingiverse.com/thing:35834

**Comment by revarbat** [comment]
Seems useful, if for no other reason than to allow breaking up large prints into assemble-able pieces.

**Comment by adrianVmariano** [comment]
Yeah, that was the point, I thought.  There's a peg version also, but that seems like it would be annoying to print due to supports.  

https://www.thingiverse.com/thing:310652

Perhaps it's a hair less obtrusive (no puzzle shape in the model)?   OF course, the locking nature of puzzle cut is nice.  

https://github.com/jernst/josl/tree/master/josl/cuts

Does some other cut lines, including zig-zag and comb.

**Comment by revarbat** [comment]
Implemented in e2e6bcf2f9a7c4fd39fcd05918770e62cab1f617
