### ISSUE TITLE
universal joint?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#59]
https://www.thingiverse.com/thing:125939

Consider adding something like this.

**Comment by revarbat** [comment]
Hmm.  Not sure if this is really needed.

```openscad

**Comment by revarbat** [comment]
```openscad
$slop=0.2;
module ujoint(r, d) {
    r = get_radius(r=r, d=d, dflt=50);
    rot_copies([[0,0,0], [180,0,90]]) {
        difference() {
            intersection() {
                union() {
                    zcyl(r=r, l=2*r, anchor=TOP);
                    ycyl(l=2*r, r=r/2);
                }
                zcyl(r=r, l=10*r);
            }
            ycyl(r=r/3, l=3*r);
            zcyl(r=r*0.75, l=r*2);
            xspread(2*r) cube([r,r*3,r*2], center=true);
        }
    }
    sphere(r=r*0.75);
    zrot_copies([0,90]) {
        xcyl(r=r/3-3*$slop, l=r*2);
    }
}
```
<img width="152" alt="Screen Shot 2019-06-27 at 3 00 03 PM" src="https://user-images.githubusercontent.com/350001/60303816-4a6ef400-98ec-11e9-9139-84a4f102ac2f.png">

**Comment by revarbat** [comment]
How often will this come up though?

**Comment by adrianVmariano** [comment]
Don't know.  Could be interesting to make some mechanism with a bunch of these.  Assuming that they print well.  But I'm OK either way with keeping it or not.

**Comment by revarbat** [comment]
```openscad

**Comment by revarbat** [comment]
Eh.  I don't see this as being a library item.
