### ISSUE TITLE
Include tolerance as a parameter in partition

### ISSUE THREAD

**Issue by traysh** [revarbat/BOSL2#593]
**Is your feature request related to a problem? Please describe.**
partitions.scad is a great module but I can't use it because after printing the 2 parts won't assemble.

**Describe the solution you'd like**
Please allow a tolerance to be defined as a parameter, so, instead of only partitioning, a small amount of material can be removed to make it possible to assemble the parts after printing
edit: a numerical parameter would be preferred than preset explicit values, as it would make it more flexible

**Describe alternatives you've considered**
An alternative is to use joiners instead, but partitioning would be more straightforward.

**Additional context**
I'm using a FDM printer, different kinds or brands of filament or printing settings would make different tolerances needed.

**Comment by revarbat** [comment]
You are describing the $slop= argument.  But it's not well documented, which is issue #433
