### ISSUE TITLE
no wiki for polyhedra.scad?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#6]
The documentation in polyhedra.scad isn't showing up on the wiki.

**Comment by revarbat** [comment]
It's there.  It just wasn't linked from the sidebar or home pages.  That's now fixed.

**Comment by adrianVmariano** [comment]
Looks like the long multi-paragraph description section didn't get interpreted correctly.  Only the first paragraph shows up.

**Comment by revarbat** [comment]
Fixed in 69cc3a76c1b70a56a97f3b9d33985ee04537250b
