### ISSUE TITLE
stroke produces weird results on 3d input

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#64]
I'd say either fix it to produce useful results or put in a check to fail in the case of 3d input.

**Comment by adrianVmariano** [comment]
heptagon = lift_plane(regular_ngon(n=7, or=10), [0,0,0], [5,0,5], [0,2,3]);
     stroke(heptagon, width=1, close=true);

**Comment by revarbat** [comment]
Added `assert()` to ensure path is 2d.  Implemented in e60648dadd99c066f56f2d7caa4129f3c7194bca
