### ISSUE TITLE
height map module

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#70]
Add height map module along these lines:

https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Tips_and_Tricks#Data_Heightmap

(We don't have this already somewhere, do we?)

**Comment by revarbat** [comment]
Already exists, though I seem to have it in the wrong docs section.

https://github.com/revarbat/BOSL2/wiki/geometry.scad#heightfield

**Comment by revarbat** [comment]
Moved it to shapes.scad.
