### ISSUE TITLE
[BUG] path_extrude2d() with unwanted gaps

### ISSUE THREAD

**Issue by 3Dietrich** [revarbat/BOSL2#702]
**Describe the bug**
there is a lot of possibilities to make it differently but I found path_extrude2d() just fine and tried to make a form like "C" extruded. But I get gaps, with angle 360 there are 3 gaps and an unwanted displaced object:
**Code To Reproduce Bug**
```
include <BOSL2/std.scad>
path3 = [ [0,0], [3,0], [5,10], [2,10] ];
// test the path
region(path3);

// this on has the most errors: 3 gaps + an unwanted, displaced object:
fwd(30)
path_extrude2d(arc(d=30, angle=360), caps=false) region(path3);

// but any other angle lead to at least one gap:
back(20) 
path_extrude2d(arc(d=30, angle=180), caps=false) region(path3);

```

**Expected behavior**
I thought path_extrude2d() would produce one straight object without gaps.

**Screenshots**
the rendered objects from the code above:
<img width="355" alt="Bildschirmfoto 2021-10-21 um 22 08 05" src="https://user-images.githubusercontent.com/4608796/138349486-8bc40958-9ecf-40a5-87d8-7d59e32845de.png">

**Additional context**
well, I know that I could angle=370 solves the problem with the first object, but.. at least one gap is still there.
- OpenSCAD Version: 2021.01 
- Other libraries used: exept BOSL2 (tested with download right now 2021 10 21) nothing used in this context.

**Comment by adrianVmariano** [comment]
Note that it's not clear path_extrude2d() should exist.  It seems like it exists only because the logic wasn't available to manage twisting in the generic path_extrude().  If that logic is added to path_extrude() then this module becomes unnecessary.  

In path_extrude() the test example works OK except that it doesn't complete the angle, so it doesn't close the circle.

**Comment by adrianVmariano** [comment]
I fixed this bug.  Added a close option to close the circle and the bug that caused the other gaps.

**Comment by 3Dietrich** [comment]
@adrianVmariano how to test your fix? I downloaded right now.. no change. Also in the [manual](https://github.com/revarbat/BOSL2/wiki/mutators.scad#module-path_extrude2d) is no change..? 
Should I just wait a bit?

**Comment by adrianVmariano** [comment]
Revar didn't merge my PR yet.  I am a little weak on git use, but I think you can find it in my fork of BOSL2 if you want to test it now.   (Or maybe you can go straight to the PR and get it from there somehow?)

**Comment by 3Dietrich** [comment]
> Revar didn't merge my pull reqest yet. 

ah! yes. I found only the merge from #714.
> I think you can find it in my fork of BOSL2 if you want to test it now. (Or maybe you can go straight to the PR and get it from there somehow?)

I can wait :)

**Comment by adrianVmariano** [comment]
module path_extrude2d(path, caps=false, closed=false) {
        assert(caps==false || closed==false, "Cannot have caps on a closed extrusion");
        thin = 0.01;
        path = deduplicate(path);
        for (p=pair(path,wrap=closed)) 
            extrude_from_to(p[0],p[1]) xflip()rot(-90)children();
        for (t=triplet(path,wrap=closed)) {
            ang = -(180-vector_angle(t)) * sign(_point_left_of_line2d(t[2],[t[0],t[1]]));
            delt = point3d(t[2] - t[1]);
            if (ang!=0)
                translate(t[1]) {
                    frame_map(y=delt, z=UP)                      
                        rotate_extrude(angle=ang)
                            if (ang<0)
                                right_half(planar=true) children();
                            else
                                left_half(planar=true) children();                          
                }
                    
        }
        if (caps) {
            move_copies([path[0],last(path)])
                rotate_extrude()
                    right_half(planar=true) children();
        }
    }

Actually there's the code for the update.  I've found that CGAL doesn't like the result, though, saying my result may not be a 2-manifold (even though all the pieces are valid).

**Comment by 3Dietrich** [comment]
works excellent!
Thank you!
