### ISSUE TITLE
Add function index, and summary doc tags

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#73]
Add an index of all functions and modules and `Summary:` doc tags to functions and modules.

**Comment by revarbat** [comment]
Added a function index.  https://github.com/revarbat/BOSL2/wiki/Index

**Comment by adrianVmariano** [comment]
Looks like a good start.  Seems like it would be good if you could determine the file you need to include from the index.   Would it make sense for the index to be listed by include file instead of alphabetical?  (Given that you can always do a search of the page to find something?)

**Comment by revarbat** [comment]
I added the file of origin for each call to the Index.
