### ISSUE TITLE
cuboid roundings incorrect if $fn not divisible by 4

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#732]
Rounding some (not all) edges gives incorrect results:

    cuboid(10, rounding=2, edges=TOP,$fn=5);
![image](https://user-images.githubusercontent.com/26014420/142263085-4593c2c2-77a3-4d5a-b8f8-79eb54880c84.png)

    cuboid(10, rounding=2, edges=TOP,$fn=25);

![image](https://user-images.githubusercontent.com/26014420/142263251-a41f953f-2b32-4d95-b543-f3422b27c939.png)

**Comment by revarbat** [comment]
I think the only way to fix this is to quantize $fn to 4 inside the internal module `corner_shape()`.

**Comment by revarbat** [comment]
Well, it may be possible to carefully align all the sub-cylinders, but I think the results will still look kind of bad compared to just quantizing $fn to 4.

**Comment by adrianVmariano** [comment]
I think forcing $fn up to the next multiple of 4 is a totally reasonable solution.

**Comment by adrianVmariano** [comment]
Consistent with what?

**Comment by revarbat** [comment]
Consistent in that both `xcyl()` and `ycyl()` should have an edge facing the same way (up or down).  I assume both `cyl()` and `zcyl()` and `cylinder()` have an edge towards X+.

**Comment by adrianVmariano** [comment]
Do zcyl and cylinder have an edge towards x+ or a line towards x+?

**Comment by revarbat** [comment]
`xcyl()` has an edge towards Z- and a face towards Z+:
<img width="453" alt="Screen Shot 2022-01-12 at 8 26 47 PM" src="https://user-images.githubusercontent.com/350001/149265881-5f39fd61-cbc6-44c4-afc4-5bdd20220e73.png">
`ycyl()` has an edge towards X+ and a face towards X-:
<img width="453" alt="Screen Shot 2022-01-12 at 8 28 07 PM" src="https://user-images.githubusercontent.com/350001/149266003-68e86cfb-5043-4beb-9fb2-befba278eeaa.png">
`zcyl()` has an edge towards X+ as well, and a face towards X-:
<img width="453" alt="Screen Shot 2022-01-12 at 8 29 08 PM" src="https://user-images.githubusercontent.com/350001/149266099-4b0357c1-f7c5-4258-8785-daaf3430cebb.png">

**Comment by revarbat** [comment]
`cyl()` and `cylinder()` are oriented like `zcyl()`.

**Comment by revarbat** [comment]
I'm thinking both `xcyl()` and `ycyl()` should have their starting edge towards Z+

**Comment by revarbat** [comment]
`cuboid()` is fixed by quantization in PR #755

**Comment by adrianVmariano** [comment]
If cylinders have starting edge towards z+ then they'll have an edge down for even $fn.  Is that ok?

**Comment by revarbat** [comment]
Original issue fixed.
