### ISSUE TITLE
Missing sp_cap() to accompany sp_neck()

### ISSUE THREAD

**Issue by pp19dd** [revarbat/BOSL2#739]
Of all the OpenSCAD thread libraries I've seen, this library is the only one that includes a very appropriate `sp_neck()` for making large jar lids (aiming for around 90-100mm diameter).  Thank you!  However, it doesn't include a corresponding sp_cap module that mates with it.  

Would it be possible to add an sp_cap() module to bottlecaps.scad ?

**Comment by adrianVmariano** [comment]
The problem is that SPI necks are based on published standards whereas SPI caps seem to be a trade secret.  This kinda thwarted my ability to do the SPI cap.  I was pondering whether to try measuring some caps to get ideas of how it works.  But wasn't sure how to proceed.   It's an obvious need.

**Comment by adrianVmariano** [comment]
I made a stab at this.  It's in PR #970.
