### ISSUE TITLE
Trivial Issue with centering things

### ISSUE THREAD

**Issue by Dorro101** [revarbat/BOSL2#765]
Hi Revar

I have a trivial issue with the constant name "CENTER". Is it possible you could add an equivalent constant "CENTRE"? I see you have done this with other constants like "BOT" and "BOTTOM"? I cannot help typing CENTRE and its drives me a little batty, especially late at night after a long coding session. I edit a lot, using UK/South African spelling, so it throws me a little.

I assumed it it would be simple to just add it to 'constants.scad', however...

![Screenshot from 2022-01-21](https://user-images.githubusercontent.com/54166678/150461720-1dd9dbe3-1c11-466a-81d3-bdb8eea9ae76.png)

Using OpenSCAD-nightly, installed using snap on Fedora 35. Only way to get OpenSCAD working without issues on my Gnome install. Tried it with my flatpak install of OpenSCAD stable, which has issues with my default desktop theme, a QT thing I guess, and throws the same error.

Thanks for your great libraries. BOSL2's attachments rock and are perfect for my current parametric project!

Ciao
Dorian

**Comment by revarbat** [comment]
The error looks like you passed `anchor="CENTER"` (a string) as opposed to `anchor=CENTER` (the presumably added constant.).

**Comment by revarbat** [comment]
This was trivial, so I added a CENTRE alias to CENTER.

**Comment by Dorro101** [comment]
Hi Revar

Thanks. I was just being an idiot. I had already declared 'CENTRE' locally as a workaround, but forgot to remove it when I changed the 'constants.scad' file. Thanks for adding, now I won't have to change it myself every time I update the code from Github.

Thanks again for your great work!!!

Ciao
Dorian
________________________________
