### ISSUE TITLE
[BUG] Syntax error on line 1136 @ geometry.scad

### ISSUE THREAD

**Issue by EV3R4** [revarbat/BOSL2#767]
**Describe the bug**
When including "BOSL2/std.scad", OpenSCAD throws `ERROR: Parser error in file "~/.local/share/OpenSCAD/libraries/BOSL2/geometry.scad", line 1136: syntax error`.
https://github.com/revarbat/BOSL2/blob/00df38a83b8d093e794355e819ab62167624d3ca/geometry.scad#L1136

**Code To Reproduce Bug**
```c
include <BOSL2/std.scad>
```

**Expected behavior**
It shouldn't throw an error.

**Additional context**
- Since commit 00df38a83b8d093e794355e819ab62167624d3ca
- OpenSCAD Version: Tried with 2019.5 and 2021.1
- Other libraries used: None

**Comment by revarbat** [comment]
The `X^Y` syntax is a newer addition to OpenSCAD.  It is significantly faster than using `pow()`.  However, it isn't supported in the current "stable" release.  I've verified it works in 2021.03.08, but we really shouldn't use syntaxes not supported by the latest stable production release, so this is, in fact, a bug.

**Comment by revarbat** [comment]
Fixed in PR #768

**Comment by revarbat** [comment]
I may have been premature.  I cannot reproduce the error on OpenSCAD 2021.01 on Mac.  What platform are you on, @EV3R4?

**Comment by adrianVmariano** [comment]
I guess another question might be: are you *sure* you tested it in 2021.1?  It works fine for me in 2021.1 under Linux.

**Comment by EV3R4** [comment]
I'm using Ubuntu 20.04.3 LTS x86_64
The error occured on 2019.05 installed via aptitude, working since 535fea37e529ab6bb1217f139d4354ccb2be08d0
2021.01 AppImage and snap are working before and after

**Comment by revarbat** [comment]
Works under 2021.01 on Mac too.
