### ISSUE TITLE
Masks for rounding rectangular holes.

### ISSUE THREAD

**Issue by revarbat** [revarbat/BOSL2#8]
We don't currently have any simple way to make rounded edges on rectangular holes.

**Comment by adrianVmariano** [comment]
You can do this using rounded_extrude.     

I think it's better to make the hole and roundover in one operation rather than to make the hole and then try to round its edges.  It's one of the reasons I've been pushing for filletting, because that's a major application for it.

**Comment by revarbat** [comment]
Added external rounding/chamfering to `cuboid()` top and bottom face edges.
Implemented in 9611a181db2814684f0fc2f61492518c6760a42f
