### ISSUE TITLE
cuboid rounding should work for non-interfering roundings even when bigger than half the edge length

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#809]
If I try to round over two edge of a cuboid with a large rounding I get the error that the roundings don't fit, which is false.  The problem is that I'm trying to make a rounding that is bigger than half the cuboid.  It should work, because to potentially conflicting roundings are turned off.  

cuboid([50,10,2],rounding=9, edges=[BACK+LEFT,BACK+RIGHT]);

This has come up several times and I've had to work around this limitation, so I think it would be worth making it fail only when the roundings *actually* conflict.  I should be able to set rounding to 10 in the above example and round the entire corner.

**Comment by revarbat** [comment]
Implemented in PR #821
