### ISSUE TITLE
offset on region bombs if return_faces=true

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#82]
I'm not sure what it should do in this case, but if you pass in a region and set return_faces to true then it gets a cryptic error.

**Comment by revarbat** [comment]
As subpaths can merge/split on `offset()`, this is very difficult to fix.  Maybe just forbid `return_faces=true` for regions.

**Comment by adrianVmariano** [comment]
Yeah, error message that `return_faces` must be false would be a solution

**Comment by revarbat** [comment]
Added assertion in e8254cec7d7bbee80f762f2cf640338e94530e63
