### ISSUE TITLE
circle spec consistency

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#830]
circle_point_tangents takes (r,cp) but circle_circle_tangents takes (c1,r1,c2,r2) so the order of center and radius is switched.  Seems like there should be a uniform convention for this.

**Comment by revarbat** [comment]
Another inconsistency... most places in the library where we give a centerpoint of a circle, we use `cp=`, but some of the circle functions use `c=`, `c1=` or `c2=` instead.

**Comment by revarbat** [comment]
Standardizing these functions on `r=, cp=`.

**Comment by revarbat** [comment]
Implemented.
