### ISSUE TITLE
should joiners user tags to handle differencing?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#852]
The joiners file has "clear" modules that are to be subtracted to clear space for the joiner.  Should this be rewritten to use tags so you can just attach the joiner with the specified tag and the space is cleared, all in one operation?  This seems more tidy. 

Also, are the multi-joiners modules needed when you can do xcopies()?

**Comment by revarbat** [comment]
Actually it'd be `xrot_copies()` due to asymmetry, but that is a valid question.

**Comment by revarbat** [comment]
Dropping the multi-joiners.

**Comment by revarbat** [comment]
Implemented in PR #855.
