### ISSUE TITLE
consolidate nema modules?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#853]
There are a bunch of nema modules for different sizes.  Should there just be a single function with a "size" argument?  Or is the current approach better?

**Comment by revarbat** [comment]
Also, having one `nema_info()` function instead of multiple data functions would be cleaner.

**Comment by adrianVmariano** [comment]
Depends:  without structures, having a bunch of unlabeled return values could be kind of hard to understand.  

Are nema data functions meant for users, or just used internally?

**Comment by revarbat** [comment]
Implemented in #922
