### ISSUE TITLE
defaults in diff() dont work

### ISSUE THREAD

**Issue by sgall17a** [revarbat/BOSL2#858]
This is from the documentation:

include <BOSL2/std.scad>
diff()
cuboid(50) {
    attach(TOP) sphere(d=40, $tags="remove");
    attach(CTR) cylinder(h=40, d=10, $tags="keep");
}

This crashes OpenSCAD because there is an undefine variable

include <BOSL2/std.scad>
diff("remove")
cuboid(50) {
    attach(TOP) sphere(d=40, $tags="remove");
    attach(CTR) cylinder(h=40, d=10, $tags="keep");
}

Does not crash but keep does not work

include <BOSL2/std.scad>
diff("remove","keep")
cuboid(50) {
    attach(TOP) sphere(d=40, $tags="remove");
    attach(CTR) cylinder(h=40, d=10, $tags="keep");
}

Works properly

[OpenSCAD](https://www.openscad.org/) version 2021.01

BOSL2. ?version I downloaded it off github about April 20

Absolutely Brilliant library BTW

**Comment by revarbat** [comment]
Defaults for `diff()` were added on April 24th.  Re-download the latest and it should work.
