### ISSUE TITLE
[BUG]Syntax error in geometry.scad

### ISSUE THREAD

**Issue by RyantHults** [revarbat/BOSL2#885]
**Describe the bug**
When including BOSL2 into a scad file, I get `ERROR: Parser error in file <path to openscad>/BOSL2/geometry.scad, line 992: syntax error`

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>
```

**Expected behavior**
no error

**Screenshots**
![openscad_2022-06-15_20-58-37](https://user-images.githubusercontent.com/4096348/173975310-625be52c-3963-4870-bea7-c2bbc91cdc30.png)

**Additional context**
- OpenSCAD Version: 2019.05 
- Other libraries used: MCAD

**Comment by RyantHults** [comment]
Looks like this was a version issue. Updating to 2021.01 fixed it. Closing.

**Comment by WyomingWill** [comment]
I'm having the same issue, still.... Also, beziers is throwing a syntax error in addition. 

![Screenshot from 2022-09-11 02-34-57](https://user-images.githubusercontent.com/10241608/189518819-a4b207e0-27f1-43f0-a960-8077caadb1ec.png)

**Comment by revarbat** [comment]
Your version of OpenSCAD is too old and doesn't support the exponent operator. Please upgrade to OpenSCAD 2021.01 or later.

**Comment by WyomingWill** [comment]
Thank you! I saw:

`assert(version_num()>=20190500, "BOSL2 requires OpenSCAD version 2019.05 or later.");`

in std.scad and thought I was safe. Works fine with OpenSCAD-2021.01-x86_64.AppImage.

Thanks again for the quick reply.
