### ISSUE TITLE
Add a constant for typographers points.

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/BOSL2#899]
**Is your feature request related to a problem? Please describe.**
The text3d.scad is a bit confusing in that the size parameter is referred to as "font size".   It actually means the size of the type in whatever the base unit of OpenScad is (normally mm).  In the world of computer type,  "font size" is traditionally measures in "points"  usually 1/72 inch or about 0.353 mm.  

**Describe the solution you'd like**
Add a constant PT or PTS to constands.scad

**Describe alternatives you've considered**
Alternatively adding a note to the documentation pointing out that the size parameter means mm.

**Example Code**
PT = INCH/72;
or
PT = 0.35278;

**Additional context**
[Wikipedia article on Typographic Points](_https://en.wikipedia.org/wiki/Point_(typography)_)

**Comment by adrianVmariano** [comment]
duplicate issue
