### ISSUE TITLE
[BUG] "butt" endcap not working as expected on arc stroke

### ISSUE THREAD

**Issue by rola25** [revarbat/BOSL2#928]
**Describe the bug**
When using "butt" as endcap for an arc with big line width, the butt is not correct

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>
path = arc(r=30, angle=120);
stroke(path, width=25, endcaps="butt");

```

**Expected behavior**
butt should be plane

**Screenshots**
![image](https://user-images.githubusercontent.com/40626700/185743429-857927bb-cae0-400f-b759-1f7220b21602.png)

- OpenSCAD Version: latest
- Other libraries used: none

**Comment by revarbat** [comment]
Ooh... tricky. The bug is that the next segment joint in from the ends is using a circle to round out the elbow of that joint, but that circle extends beyond the end of the line. The solution will be to use a pie slice instead of a circle. It'll be interesting to see how this affects drawing speed.
