### ISSUE TITLE
clipping textured cyl fails: ERROR: The given mesh is not closed! Unable to convert to CGAL_Nef_Polyhedron. 

### ISSUE THREAD

**Issue by jmlzone** [revarbat/BOSL2#935]
Maybe I am doing something dumb, but I get the error with this simple code:
include <BOSL2/std.scad>
module clipped_radius(h, r, t) {
   l=r-t;
   right_half (x=l) cyl(h=h, r=r, texture="diamonds", tex_size=[5,5]);
}
clipped_radius(100,27,7);
 works fine in preview, but when rendering I get the error.

**Comment by revarbat** [comment]
This is a legitimate bug, and can be seen clearly by viewing the following code in Thrown Together mode:
```openscad
cyl(h=10, r=10, texture="diamonds", tex_size=[5,5]);
```
