### ISSUE TITLE
WARNING: variable edges not specified as parameter

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/BOSL2#937]
I'm not sure whether I should worry about this warning or not.   I can't find any other references to "variable edges".

Here's a code code snippet that throws the warning:

`include <BOSL2/std.scad>

gnss = [25,25,6.5];
pad  = [4.4, gnss.y * 0.6, gnss.y * 0.6];
pad2  = [4.4, gnss.y * 0.3, gnss.y * 0.4];

prismoid(size1 = [pad.y,pad.z], size2 = [pad2.y, pad2.z], shift = [(pad2.y - pad.y)/2,0],
			h = pad.x, rounding = 2, edges = "Z", anchor = LEFT+BOT);
`

What am I doing wrong that causes it?

**Comment by adrianVmariano** [comment]
What you are doing is passing the "edges" parameter to prismoid(), which doesn't accept that parameter.   OpenSCAD alerts you that edges is not a parameter with that warning.   Note that prismoid can **only** round the "Z" edges, so no edges parameter is used.

**Comment by RAMilewski** [comment]
Aha!  Noob pilot error.  Thank you.
