### ISSUE TITLE
[BUG]  screws.scad broken - always renders unwanted 2D geometry.

### ISSUE THREAD

**Issue by IanM-2022** [revarbat/BOSL2#939]
**Describe the bug**
Including screws.scad (as per any screws.scad example from the wiki: https://github.com/revarbat/BOSL2/wiki/screws.scad#module-screw ) and attempting to use screw() renders the  example 6 "gap between nut and bolt at the loosest tolerance" 2D objects rather than the specified  screw.   Commenting out the screw() line does not remove the incorrect 2D objects. 

Reverting to a previous BOSL2 (2022-08-15) renders the screw correctly with no changes to the code below.

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>
include <BOSL2/screws.scad>
screw("M10", length=20, head="hex");
```

**Expected behavior**
Correctly rendered M10 hex headed machine screw.

**Screenshots**
The incorrect render:
![screws bug](https://user-images.githubusercontent.com/106455929/188412283-5eef8728-b1da-4184-9de4-fc8f005e846d.png)
The correct render with the 2022-08-15 BOSL2:
![screws expected](https://user-images.githubusercontent.com/106455929/188414665-a2aad511-9820-47ac-8023-c065ac66927d.png)

**Comment by adrianVmariano** [comment]
This is fixed in PR 940.
