### ISSUE TITLE
Function Index link to texture() misplaced.

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/BOSL2#948]
The texture() link in the Function Index points to example 12 of rot_resample().

**Comment by revarbat** [comment]
This is not a bug in the BOSL2 docs.  The link is correct, the anchor is correct, and my particular web browser (Safari) takes me to the correct location on the page.

FireFox has a known bug where it behaves as you describe, but if you reload the page after a moment, it goes to the correct place. The known workarounds to the bug involve JavaScript code that I cannot include in GitHub's Wiki pages, so there's not much I can do.
