### ISSUE TITLE
projection() missing from Function Index

### ISSUE THREAD

**Issue by RAMilewski** [revarbat/BOSL2#949]
Example 1 in threaded_rot() reads:

     include <BOSL2/std.scad>
     include <BOSL2/threading.scad>
     projection(cut=true)
     threaded_rod(d=10, l=15, pitch=1.5, orient=BACK);

But projection() is missing from the Function Index.

**Comment by revarbat** [comment]
That's because `projection()` is an OpenSCAD built-in command, and is not part of the BOSL2 library.
