### ISSUE TITLE
cyl() needs internal diam/radius args

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#955]
There should be id/ir args for cyl that specify internal diameter or radius.

**Comment by revarbat** [comment]
So that `cyl(l=10,ir=10);` is the same as `cyl(l=10,r=10,circum=true);`?

**Comment by adrianVmariano** [comment]
I didn't see the circum arg.  (And I was even looking for it.)    I guess it's fine, then.  I don't know if there's ever a case where someone would want `id1=1, od2=20` which would give a bit more flexibility.

**Comment by adrianVmariano** [comment]
I guess there is a question about API consistency here, though, since some modules use `id` and some use `circum`.

**Comment by adrianVmariano** [comment]
I suppose one solution to this problem might be to make all the modules support both forms.

**Comment by adrianVmariano** [comment]
I took a look at modules and current interface.  The only one that supports id/od is regular_ngon.  Everything else just takes circum.

**Comment by revarbat** [comment]
Which begs the question, should `regular_ngon()` use `circum=`?

**Comment by adrianVmariano** [comment]
Well, regular n_gon is making a regular n_gon.  It makes it the exact size you say.  So the concept of circumscribing doesn't really make sense.  The other operations are all making rounded forms that are being approximated, so saying that the approximation circumscribes the true form makes sense.

Other modules with id/ir include star and tube, where it also makes sense that there is an inner measurement.

**Comment by adrianVmariano** [comment]
We could add circum as an option to regular_ngon just for consistency, and leave ir/id available also.
