### ISSUE TITLE
[BUG] path_pos_from_start is absent

### ISSUE THREAD

**Issue by karabas2011** [revarbat/BOSL2#967]
After upgrading to last BOLS2 my code stopped working as it does not find 
"path_pos_from_start" anymore. Maybe it is renamed to something else.
I tried to use path_cut but failed.
What I need to use in new BOLS2 insteed?
My code is below. 
p is  path for tube "extruding"
pb is path of diameters of the tube.

In general I want to build tubes with two curve approach and place on them parts controled by given length from the top of the path. That is why I cannot use "stroke" but use path_pos_from_start and path_spread.

module place_item(l,angle){
    kkk0= path_pos_from_start(pb,l,closed=false);
    kkk_bt0 = lerp(pb[kkk0[0]], pb[(kkk0[0]+1)%len(pb)], kkk0[1]);
    path_spread(p, 1,1,kkk_bt0[1]) 
    rotate([90,0,0]) children(0);
    //cylinder(d=5,h=3.5,$fn=120);
}

```
module tube(){
union(){
 for (i=[1:1:n-1]){
    diam0= path_pos_from_start(pb,(i-1)*bl/n,closed=false);
    diam  = path_pos_from_start(pb,i*bl/n,closed=false);

    bt0 = lerp(  pb[diam0[0]],   pb[(diam0[0]+1)%len(pb)],   diam0[1] );
    bt   = lerp(  pb[diam[0]],     pb[(diam[0]+1)%len(pb)],     diam[1]);  

   hull(){  
        path_spread(p, 1,1,bt0[1], rotate_children=true,closed=false) rotate(90,[0,1,0])cylinder(d=bt0[0],h=0.1,$fn=50);
        path_spread(p, 1,1,  bt[1], rotate_children=true,closed=false) rotate(90,[0,1,0])cylinder(d=bt[0],h=0.1,$fn=50);
   }
 
 } 
 } 
```

**Comment by karabas2011** [comment]
Thank you very much for solution.
I modified my code and it works.
To place item at given length I must to resample at needed pecision.If 1mm is enough I use   module place_item(l,angle){       pbr = resample_path(pb, ceil(path_length(pb)+1), closed=false);      path_spread(p, 1,1,pbr[l][1] ) rotate([90,0,0]) children(0);    }
I attached new code. 

Now I am trying to undestand why my tube does not start at 0,0 of the path and why it stopped at points depending of NSee attached pic.
    On Wednesday, October 12, 2022 at 04:58:20 PM GMT+3, adrianVmariano ***@***.***> wrote:  
 
 


As I mentioned on the forum, I don't think your code works as is. It appears you should be using lookup instead of path_pos_from_start. But since I maybe don't know what you're trying to do, I could be wrong.

If you want it to continue doing the thing it does right now you can replace path_pos_from_start with resample_path in the above fragment. In general, path_cut can replace the old function, but you have to read the manual because it is not a drop-in replacement. It produces the paths instead of the distances, so you need to use last() or [0] to get the entry you need.
 module tube(w){
   pbr = resample_path(pb, n+1, closed=false);
   for (i=[1:1:n-1]){
      hull(){  
         path_spread(p, 1,1,pbr[i-1][1], rotate_children=true,closed=false) rotate(90,[0,1,0])cylinder(d=pbr[i-1][0]+w,h=0.1,$fn=50);
         path_spread(p, 1,1,pbr[i][1], rotate_children=true,closed=false) rotate(90,[0,1,0])cylinder(d=pbr[i][0]+w,h=0.1,$fn=50);
      }
   } 
 }    

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
[BUG] path_pos_from_start is absent · Issue #967 · revarbat/BOSL2

After upgrading to last BOLS2 my code stopped working as it does not find "path_pos_from_start" anymore. Maybe i...
 |

 |

 |





| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build software better, together

GitHub is where people build software. More than 83 million people use GitHub to discover, fork, and contribute ...
 |

 |

 |

**Comment by adrianVmariano** [comment]
I mean, it works in that it produces the same result as before, but as I said before, I believe it does the wrong thing.  That is, your code does not actually work.  But to really understand this, you need to explain what exactly is the meaning of pb.  I cannot think of a natural meaning for pb such that your code is correct, but again, I do not know your ultimate intent.
