### ISSUE TITLE
attachments for irregular objects, included rounded_sweep

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL2#98]
General attachment strategy for weird shaped objects.  Could apply to supershape, rounded_sweep.

Thinking the +x attachment for a 2d shape should be the point where the x value of the shape is maximal.  Or if there are multiple such points, the average of the two most extreme cases (e.g. the "top right" and "bottom right")

**Comment by revarbat** [comment]
I actually implemented VNF and path based attachments a while ago.
