### ISSUE TITLE
Faces are missing in the result of vnf_halfspace

### ISSUE THREAD

**Issue by herdima** [revarbat/BOSL2#980]
In all three generated intersections, faces are missing in the mid of the intersection area:
`vnf=sphere(r=50, style="icosa", $fn=16);
%vnf_polyhedron(vnf);
hsps= [[0,1,0,0],[0,0,-1,0],[-1,0,0,0]];
for(i=idx(hsps))
translate([110*(i+1),0,0])
vnf_polyhedron(vnf_halfspace(hsps[i], vnf));`
I did not find smaller examples for this behavior when experimenting with tetrahedra, cubes and various double cones.
![BOSL2 bug in vnf_halfspace](https://user-images.githubusercontent.com/82678374/198549845-06319b4b-96ab-4490-9acd-449a5a30b9bb.png)

**Comment by adrianVmariano** [comment]
Seems to be a rounding problem.  Looks like solution is to change

         inside = [for(x=vnf[0]) plane*[each x,-1] >= 0 ? 1 : 0],

to

         inside = [for(x=vnf[0]) plane*[each x,-1] >= -EPSILON ? 1 : 0],

in vnf_halfspace().

**Comment by adrianVmariano** [comment]
Fixed in #983
