### ISSUE TITLE
[BUG] sortidx() returns the list to be sorted, not the sorted index, when list is one-element long

### ISSUE THREAD

**Issue by jon-gilbert** [revarbat/BOSL2#999]
**Describe the bug**
When sorting indexes for a one-element list, `sortidx()` returns the list, not the index. 

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>

idxs = sortidx(["d", "e"]);
idxs_comp = [0, 1];
assert(idxs == idxs_comp, str("idxs returned must be: ", idxs_comp, ": ", idxs));

idxs2 = sortidx([]);
idxs2_comp = [];
assert(idxs2 == idxs2_comp, str("idxs returned must be: ", idxs2_comp, ": ", idxs2));

idxs3 = sortidx(["d"]);
idxs3_comp = [0];
assert(idxs3 == idxs3_comp, str("idxs returned must be: ", idxs3_comp, ": ", idxs3));

```

**Expected behavior**
The documentation for `sortidx()` doesn't say there's a degenerate case when `lst` has zero or one element, giving the expectation that when there are no elements in `lst`, an empty index list is returned (this happens); and, that when there is only one element in `lst`, only one index list is returned (this is *not* what happens). 

The expectation would be that `sortidx()` either attempts to sort the indexes of a one-element list and return the index (which would always be `[0]`); or, take a shortcut and realize that with only one element there's only one response to return (again, `[0]`). 

Working around this requires something akin to:
```
sorted_indexes = (len(lst) == 1) 
   ? [0]
   : sortidx(lst);
```

**Additional context**
- OpenSCAD Version: 2021.01 (OpenSCAD/2021.01 (Windows(TM) 10.0 SP 0.0 NTW 1 MSDN 724833))
- Other libraries used: BOSL2 (via version.scad): 2.0.652 (pulled from BOSL2-master.zip on or about 2022/10/02)

**Comment by adrianVmariano** [comment]
Yeah, definitely a bug.  Actually caused by a special case check for length <=1, where it then returns the wrong answer.   Fixed this in the PR and added regression tests for single element inputs.
